### ISSUE TITLE
Option to silently ignore invalid requests

### ISSUE THREAD

**Issue by winduptoy** [share/sharedb#104]
I'm using a single websocket to communicate between my client and ShareDB server. In addition to ShareDB operations, I'm doing some other manual stuff over the websocket.

When I send my own requests over the websocket, ShareDB immediately complains and responds with `4000 "Invalid or unknown message"`.

How would I filter those custom messages out of the websocket that ShareDB is listening to before it gets to ShareDB, or make ShareDB silently ignore them?

**Comment by nateps** [comment]
Custom message passing can be implemented on top of the message 'receive' client event / middleware hook:

Server:
```
backend.use('receive', function(request, next) {
    var data = request.data;
    if (data.myApp) {
      // Handle app specific messages and don't call next
      return;
    }
    // Call next to pass other messages to ShareDB
    next();
  });
```

Client:
``` js
connection.on('receive', function(request) {
  var message = request.data;
  if (message.myApp) {
    request.data = null;
    // Handle app specific message
  }
});
```

Send a message from client:
``` js
connection.send({
  myApp: 'messageType',
  ...
});
```

Send a message from server:
``` js
agent.send({
  myApp: 'messageType',
  ...
});
```

The agent is available in all middleware, so on the server you could send a message in reply to a message from the client, or send a message to the client from the 'connect' middleware as soon as the client connects, for example.

Let me know if that solves your issue!

**Comment by RisingGeek** [comment]
Is there any way to send a message from the server to all connected clients? I think `agent.send` will send reply to only 1 client. Am I correct?

**Comment by alecgibson** [comment]
@RisingGeek this doesn't sound related to this issue? What's your use case here?

**Comment by alecgibson** [comment]
I'm not sure I understand what video calling has to do with ShareDB? Do you mean you're trying to send custom messages down the same socket ShareDB is using? In theory it's possible, although probably not advised. Can't you just open up a separate websocket, and send messages using whatever websocket protocol you want?

**Comment by RisingGeek** [comment]
Yes, I was sending custom message in the same socket that sharedb is using. Thanks for the advice. I will use a separate websocket.

**Comment by yaroslavputria** [comment]
Hi @nateps ,

Why do you set request.data to null?

> Client:
> 
> ```js
> connection.on('receive', function(request) {
>   var data = request.data;
>   if (data.myApp) {
>     request.data = null;
>     // Handle app specific message
>   }
> });
> ```

**Comment by ajay-wohlig** [comment]
> Custom message passing can be implemented on top of the message 'receive' client event / middleware hook:
> 
> Server:
> 
> ```js
> backend.use('receive', function(request, next) {
>   var data = request.data;
>   if (data.myApp) {
>     // Handle app specific messages and don't call next
>     return;
>   }
>   // Call next to pass other messages to ShareDB
>   next();
> });
> ```
> 
> Client:
> 
> ```js
> connection.on('receive', function(request) {
>   var data = request.data;
>   if (data.myApp) {
>     request.data = null;
>     // Handle app specific message
>   }
> });
> ```
> 
> Send a message from client:
> 
> ```js
> connection.send({
>   myApp: 'messageType',
>   ...
> });
> ```
> 
> Send a message from server:
> 
> ```js
> agent.send({
>   myApp: 'messageType',
>   ...
> });
> ```
> 
> The agent is available in all middleware, so on the server you could send a message in reply to a message from the client, or send a message to the client from the 'connect' middleware as soon as the client connects, for example.
> 
> Let me know if that solves your issue!

I have applied this for passing custom messages but it gives an error `Ignoring unrecognized message {` while sending message from server
