### ISSUE TITLE
Getting metadata for operations

### ISSUE THREAD

**Issue by kbadk** [share/sharedb#106]
I recently [requested metadata to be included in sharedb-mongo](https://github.com/share/sharedb-mongo/issues/42) and [it was made possible shortly after](https://github.com/share/sharedb-mongo/pull/44) by adding an `options` parameter.

However, I'm not quite sure how to actually get the metadata out. The `options` parameter was added to  [`ShareDbMongo.prototype.getOps`](https://github.com/share/sharedb-mongo/blob/master/index.js#L347-L366):

``` javascript
ShareDbMongo.prototype.getOps = function(collectionName, id, from, to, options, callback) {
  var self = this;
  this._getSnapshotOpLink(collectionName, id, function(err, doc) {
    if (err) return callback(err);
    if (doc) {
      if (isCurrentVersion(doc, from)) {
        return callback(null, []);
      }
      var err = doc && checkDocHasOp(collectionName, id, doc);
      if (err) return callback(err);
    }
    self._getOps(collectionName, id, from, options, function(err, ops) {
      if (err) return callback(err);
      var filtered = filterOps(ops, doc, to);
      var err = checkOpsFrom(collectionName, id, filtered, from);
      if (err) return callback(err);
      callback(null, filtered);
    });
  });
};
```

But unfortuntaely, the options don't seem to be passed over from ShareDB itself. [`Backend.prototype.getOps`](https://github.com/share/sharedb/blob/master/lib/backend.js#L225-L246) does not take any `options` parameter and just passes through `null` as options to sharedb-mongo (through `backend.db.getOps`):

``` javascript
Backend.prototype.getOps = function(agent, index, id, from, to, callback) {
  var start = Date.now();
  var projection = this.projections[index];
  var collection = (projection) ? projection.target : index;
  var backend = this;
  var request = {
    agent: agent,
    index: index,
    collection: collection,
    id: id,
    from: from,
    to: to
  };
  backend.db.getOps(collection, id, from, to, null, function(err, ops) {
    if (err) return callback(err);
    backend._sanitizeOps(agent, projection, collection, id, ops, function(err) {
      if (err) return callback(err);
      backend.emit('timing', 'getOps', Date.now() - start, request);
      callback(err, ops);
    });
  });
};
```

How am I supposed to pass options (to get metadata) to sharedb-mongo without modifying the ShareDB source code?

**Comment by kbadk** [comment]
Is this being addressed?

**Comment by curran** [comment]
Can you get them out via a straight up Mongo query?

**Comment by kbadk** [comment]
@curran It's in the database, so sure, I suppose you could. However, when I've needed it, I've just changed [L239 in `./lib/backend.js`](https://github.com/share/sharedb/blob/master/lib/backend.js#L239):

```javascript
backend.db.getOps(collection, id, from, to, null, function(err, ops) {
```
to
```javascript
backend.db.getOps(collection, id, from, to, { metadata: 1 }, function(err, ops) {
```
It gets the job done, but it's quite nasty to modify the library, and something you have to remember to do every time you update sharedb, but since the project is dead now, well...

**Comment by curran** [comment]
@kbadk Oh nice! Thanks for sharing that snippet.

It would be great to add a way of passing the options in through ShareDB. Maybe one more argument can be added to `Backend.prototype`? So the signature could be:

 * `Backend.prototype.getOps = function(agent, index, id, from, to, callback)`
 * or `Backend.prototype.getOps = function(agent, index, id, from, to, options, callback)`

Would you be willing to put together a PR that does something like this?

@nateps Any thoughts on an enhancement like this? Would a PR be welcome? Introducing a change like this would help improve the perception that ShareDB is a dead project, which seems to be quite widespread.

**Comment by alecgibson** [comment]
This would be solved by: https://github.com/share/sharedb/pull/215
