### ISSUE TITLE
Leaderboard Demo Missing Dependency

### ISSUE THREAD

**Issue by curran** [share/sharedb#116]
When I tried to run the leaderboard demo, I noticed that `sharedb-mingo-memory` is required in server/index.js, but is not in `package.json`.

**Comment by curran** [comment]
I believe this will also close #89

**Comment by sshadmand** [comment]
Following the intsall/run instructions in example/leaderboard gives me a "missing script: build" dependency error:
![screen shot 2016-09-14 at 3 59 30 pm](https://cloud.githubusercontent.com/assets/68735/18532960/6ba14250-7a94-11e6-86f7-33453ca08bd9.png)

**Comment by sshadmand** [comment]
Got it working:

Make sure you are in the right directory and then run

```
> npm install
> npm update
> npm run build
> npm start
```
