### ISSUE TITLE
issue with migrating old ot-text documents to sharedb v1

### ISSUE THREAD

**Issue by kutyepov** [share/sharedb#124]
I have upgraded from sharejs v0.7 to sharedb v1.0.0-beta.5 and am trying to get existing mongo db work with sharedb v1.

I took a _textarea_ example and connected it to my sharedb backend. 

```
var sharedb = require('sharedb/lib/client');
var StringBinding = require('sharedb-string-binding');
var socket = new WebSocket('ws://localhost:7008');
var connection = new sharedb.Connection(socket);

var doc = connection.get('my-old-collection', 'my-old-doc');
console.log('doc', doc);
doc.subscribe(function(err) {
  console.log('doc', doc);
  console.log('err', err);
  if (err) throw err;
  var element = document.querySelector('textarea');
  var binding = new StringBinding(element, doc);
  binding.setup();
});
```

It fails with: 
```
Uncaught ShareDBError: Missing type undefined
EventEmitter.emit @ bundle.js:79
(anonymous function) @ bundle.js:1896 
Item.run @ bundle.js:1635
drainQueue @ bundle.js:1605
```

This is the doc I am trying to get:

```
{
    "_id": "my-old-doc",
    "_data": "my super awesome text data",
    "_type": "http://sharejs.org/types/textv1",
    "_v": 0,
    "_m": {
        "mtime": 1474920210402,
        "ctime": 1474920210402
    }
}
```

It is missing the new "_O" property, which is ok according to the documentation. I assume that the issue is with:  "_type": "http://sharejs.org/types/textv1", so I replaced it with  "_type": "http://sharejs.org/types/JSONv0", which is default for new docs if different was not provided to doc.create() function. Such monkey patching of mongodb document allowed frontend to render the document to text area, yet OTs won't work. For instance, if I type anything, it won't go to mongo.

What am I doing wrong? What is the proper what to get sharejs docs work with sharedb?

**Comment by kutyepov** [comment]
Just in case here is the code from backed: 

var config = require('../../config');
var Duplex = require('stream').Duplex;
var ShareDB = require('sharedb');
var db = require('sharedb-mongo');
var WebSocketJSONStream = require('websocket-json-stream');
var share = ShareDB({db: db(config.db.url)});

```
function ShareHandler(wss) {
    if (!(this instanceof ShareHandler)) {
        wss.on('connection', function (ws, req) {
            var stream = new WebSocketJSONStream(ws);
            share.listen(stream);
        });
    }
}
```

and one more note:

Everything works fine if I create brand-new document using doc.create() fuctions.

**Comment by kutyepov** [comment]
I got it :) 

npm install ot-text --save

var otText = require('ot-text');
sharedb.types.register(otText.type);


did the trick

**Comment by adelriosantiago** [comment]
@kutyepov May I see how you `doc.create()` the document? Is it need to add the new type or just `sharedb.types.register` is enough?

**Comment by alecgibson** [comment]
@adelriosantiago if you're using any type other than `json0`, you'll need to [register it][1]. `doc.create` works no differently on the server than it does on a remote client.

[1]: https://github.com/share/sharedb#err_doc_type_not_recognized
