### ISSUE TITLE
sharedb how to apply it for angularjs ? counter example

### ISSUE THREAD

**Issue by serip88** [share/sharedb#126]
Hi, i'm try to apply angularjs for counter example, but I cannot listen "doc" object in angular controller 
 
**budle.js**
```
doc.on('op', showNumbers); 
    function showNumbers() { 
    document.querySelector('#num-clicks').textContent = doc.data.numClicks; 
};
```
 
**angular controller** => it's not work T_T , anyone can help me or is there any solution better?
 @avital : Plz help
```
doc.on('op', function() {
    $scope.test = doc.data ;
});
```

**Comment by serip88** [comment]
Oh sorry, it can listen
it's my fault, just problem about cannot showing $scope.test to UI

```
doc.on('op', function() {
    console.log(doc.data);// lol
    $scope.test = doc.data ;
});
```

Thanks , I will close this question

**Comment by jrbecart** [comment]
How you implement shareDB with AngularJS?
