### ISSUE TITLE
Cancel doc.subscribe

### ISSUE THREAD

**Issue by gaborsar** [share/sharedb#139]
Is there a way to cancel doc.subscribe?

**Comment by zag2art** [comment]
use unsubscribe - https://github.com/share/sharedb/blob/master/lib/client/doc.js#L23

**Comment by gaborsar** [comment]
@zag2art That is not the same. I am not asking how can I unsubscribe, but how can I cancel a subscribe request that is in progress?
Background: I use ShareDB with React, and I update the initial state of a component in the subscribe method's success callback. In certain scenarios, the component can unmount before the subscribe request finishes, and therefore setting the initial state of it leads to warning messages. The suggested solution to this (by React) is to use cancellable Promises and cancel them before the component unmounts. Of course, a better solution would be to move doc out of the component (to redux or flux), but cancellation still would be a good temporary solution.

**Comment by zag2art** [comment]
Got the idea. Don't think there is already the kind of method. At least I haven't find it. Maybe the authors can clarify.

**Comment by gaborsar** [comment]
@zag2art Thank you anyway, I guess I have to move the do into a separate manager module that wraps it with Promises.

**Comment by gaborsar** [comment]
Note: This issue can be closed.
