### ISSUE TITLE
Async validation

### ISSUE THREAD

**Issue by vmakhaev** [share/sharedb#14]
There are a lot of use cases where we need to use async validation logic with Racer: using data from database (model.fetch is async) for validation, using data from another async external sources.

Problem is that preValidate and validate functions are sync. So all our validation logic should be sync also. For example, we can not change racer-access plugin to support async validation, because it uses sync preValidate function.

Long time ago there was a PR to change this situation: https://github.com/share/livedb/pull/5 where @josephg  said that async validation will impact performance.
I created new Issue to discus it from scratch.

What is the way to have async validation with Racer?

**Comment by nateps** [comment]
This is now supported in sharedb, which does everything with the same async middleware pattern. Documentation is needed.

**Comment by vmakhaev** [comment]
Better late than never. :smile: 
Happy new year, @nateps
