### ISSUE TITLE
Is the project alive?

### ISSUE THREAD

**Issue by mogarick** [share/sharedb#141]
Hi,
There's not been activity since last December 2016. I've also noticed http://sharejs.org/ is not resolving at this time so I'm wondering if this project is still alive or has been abandoned.
If the project has been abandoned it would be a good gesture to the community to state that in the readme.md.

**Comment by rkstedman** [comment]
ShareDB has not been abandoned. The sharejs.org website was taken down when ShareJS split into two projects.

https://josephg.com/blog/forki/

> What is currently ShareJS master (v0.7) will be combined with livedb and renamed sharedb. Nate & his team at Lever will run sharedb (as they've been doing for the past year). It will be updated to only support JSON documents at the root level - which simplifies a lot of code. (JSON documents support subdocuments with arbitrary OT types anyway, so there won't be any loss in functionality.) Nate is also talking about merging the web client code into the repo with livedb.

> Meanwhile I'm going to revert sharejs back to the 0.6 codebase and modernise the whole thing. The API should stay (more or less) the same as it was at v0.6, although I'm going to merge the cursors branch in.

**Comment by Romainpetit** [comment]
@rkstedman http://derbyjs.com/ still shows a link to http://sharejs.org/ which is a 404 since you took it down. That's pretty confusing.
You could setup a redirect somewhere ( your [article](https://josephg.com/blog/forki/) ? ), or update the [derby-site](https://github.com/derbyjs/derby-site) repo itself to show an explanation instead of the dead link.

**Comment by curran** [comment]
@rkstedman Thanks for being the public face of ShareDB :smile:

I have a few questions related to this issue.

 * Is there any roadmap document that clarifies what's holding back the 1.0 release?
 * Is there anyone leading the project since @nateps dropped off the map in December?

Thank you.

**Comment by rkstedman** [comment]
@Romainpetit Thanks for pointing out the bad link -- and your suggestions to fix it! I'll see if I can make those improvements soon.

**Comment by rkstedman** [comment]
@curran Thanks for your questions and support 😄! I don't know of any roadmap document -- I can check with Nate and confirm, but I wouldn't get your hopes up 😢. @nateps is still leading the project  but his role at Lever is tends to take him away from ShareDB development.

**Comment by curran** [comment]
@rkstedman Sure, I understand. Thanks for your response.

**Comment by curran** [comment]
I think this issue can be closed. There are consistently responses from @rkstedman and @nateps , including merging of pull requests.
