### ISSUE TITLE
Sending Ping frame through WebSocket

### ISSUE THREAD

**Issue by prenaudin** [share/sharedb#142]
I would like to send a ping action ( `socket.send('{}')` or  `socket.send('[]')`) but ShareDB continues to respond with an `Ignoring unrecognized message` error ( error 4000 ).

Could we add something for a custom action ( for example `{ a: 'ping' }` ) that could then be ignored by the server? Then it would be easier to identify the connected client without having to first respond to an error.

Do you have any other thoughts about developing a ping frame that works with ShareDB?

**Comment by kiejo** [comment]
Check out this comment: https://github.com/websockets/ws/pull/635#issuecomment-281026825

You could use `socket.ping('', false, true)` and `socket.on('pong', () => console.log('hello'))` on the server. This is part of the WebSocket protocol meaning that the `pong` message is automatically sent by the client. I think it should work with ShareDB as these message are not treated as normal messages.

**Comment by zag2art** [comment]
Also, you can use the idea that is behind the module - https://github.com/BBWeb/racer-rpc
The idea is to use the sharedb's extraDbs. You can specify your own extraDb on the server and send it messages from the client and back. They used it to implement their own RPC.

**Comment by prenaudin** [comment]
Well guys, thank you for you fast an accurate answer:

@kiejo I tried this solution on the backend and it worked perfectly.

@zag2art It took me some time to figure out how to do it without having to write a full custom backend and I came up with just:

Backend
```javascript
new ShareDB({
  extraDbs: {
   ping: { query: () => { /* do nothing */  } }
  }
})
```

Frontend
```javascript
// Create a custom ping query 
const query = connection.createFetchQuery('ping', '', { db: 'ping' }, () => {})
query.destroy()
```

I just wrote it down if someone need these in the future ;)
Thank you again ✨

**Comment by erlendjones** [comment]
Had a similar need myself, but also wanted do use other custom functions. Ended up using a middleware to handle the requests, while also silencing the warning.

```
var customApiHandler(req, next){
  // 
};

share.use('receive', function(req, next){
    var data = req.data || {};
    switch(data.a){
      case 'heartbeat': break;
      case 'custom-api': customApiHandler(req); break;
      default: next(); break;
   }
});
```

Make sure you don't override any of the ShareDB-message-types defined in connection.js
```
Connection.prototype.handleMessage = function(message) {
    case 'init':
    case 'qf':
    case 'qs':
    case 'qu':
    case 'q':
    case 'bf':
    case 'bs':
    case 'bu':
    case 'f':
    case 's':
    case 'u':
    case 'op':
}
```
