### ISSUE TITLE
Renaming documents

### ISSUE THREAD

**Issue by nickasd** [share/sharedb#143]
Hi and thank you so much for this awesome library. I was wondering whether it would be possible to implement some kind of file manager, so that a client can subscribe to a collection named "files" and get updates whenever a document is added or removed. What is apparently missing is the ability to rename a document. Could this feature be added to a future release or should I store each document's filename as a property in the JSON object?

**Comment by curran** [comment]
I had to implement something similar.

My solution was to assign each document a permanent id, generated using [node-uuid](https://github.com/kelektiv/node-uuid), then have the "name" of the document be a mutable property.

**Comment by Nickasd** [comment]
Thanks for confirming, that's what I'm going to do.

**Comment by Nickasd** [comment]
Thanks for confirming, that's what I'm going to do.
Out of curiosity, do you use node-uuid on the client or the server? My idea was providing a static document id on the client (say, "new_file") when creating a new document and replacing it with uuid.v1() on the server, but it seems like the client doesn't even send the request to the server if that document id already exists.

**Comment by curran** [comment]
I'm using it on the client, and depending on its randomness for avoiding collisions.

**Comment by Nickasd** [comment]
I was just going to ask how one could efficiently be notified about filename changes in such a scenario and was positively surprised of finding out about the undocumented `sharedb.addProjection(projectedCollection, underlyingCollection, fields)` after having a look at #135. With such a projected collection, I would then be able to create a subscribe query which only notifies about changes to a document's `name` field.
Unfortunately such a query doesn't fire update events. It would be interesting to know if this is something in development ... or if there is an alternative solution to this problem.

**Comment by curran** [comment]
FWIW I added documentation for projections in the pending PR https://github.com/share/sharedb/pull/154

Perhaps this issue can be closed? If not, can you clarify the exact issue with ShareDB?

**Comment by Nickasd** [comment]
In the documentation you mention `addProjection`  with two different signatures, I think you forgot to remove the third argument from the second example.
I still don't know if the lack of 'changed' events is a bug or not for projections, do you know something about that? Otherwise a client cannot be notified about renamed documents without subscribing to each single one.

**Comment by curran** [comment]
@Nickasd Thanks a ton for the close reading! I went back and fixed that error re: different signatures.

I believe, just like with real collections, if you want to be notified when any document changes, you'll need to subscribe to each and every individual document individually, the use `on('op', ...)`. There may be another way that I don't know about.

**Comment by Nickasd** [comment]
You're welcome! And thanks for your suggestions.
Subscribing to each document is a possibility, but then each client will have the whole collection of files in memory only to be notified about filename changes. This can be quite inefficient when the collection is big or the client wants to open only few files.

**Comment by curran** [comment]
Right, it seems like there should be another way that's more efficient. If you use a projection with just the name field, only the name field will be loaded into memory for each document, and I think you can use the `Document` API on elements of projections, so I *think* to subscribe to name changes across all documents, you could do it with only loading the projected documents with names only.

But still, it could be a lot of documents. Have you considered using the middleware? You can trigger some code any time a name change flows through the system by adding middleware that checks ops.

```js
sharedb.use('apply', (request, done) => {
  console.log(request.op);
  if(isNameChange(request.op)){
    console.log("name changed");
  }
  done();
});
```

I'm not sure how this would play out with your use case, but it's one option for listening for changes.

**Comment by Nickasd** [comment]
By using the projection I'm able to get all the filenames, but the problem is that in a projection subscription there are no events signalling when a name changes (as opposed to collection subscriptions), only the 'ready' event is fired.
Using the middleware could be a workaround, but then the server would have to notify the clients (on another WebSocket?), handle concurrent filename changes ... and maybe there's other issues I cannot think of at the moment.

**Comment by curran** [comment]
@nateps @rkstedman [issue tending note] I think this issue can be closed, as it's a question on how to use ShareDB, not a feature request or bug with ShareDB itself.

**Comment by rkstedman** [comment]
Thanks @curran!

**Comment by curran** [comment]
Thanks @rkstedman !
