### ISSUE TITLE
1.0 Release

### ISSUE THREAD

**Issue by curran** [share/sharedb#144]
The project has been in 1.0 beta for some time now.

As I understand it, the current version is actually production-ready.

What's holding back a 1.0 release?

**Comment by curran** [comment]
Hi @nateps ,

It seems ShareDB is "baked", as in production-ready and hardened for use.

It may be worth showing some signs of life on the project and releasing the current codebase as 1.0.

Any blockers come to mind?

Thank you.

**Comment by curran** [comment]
Greetings @nateps @rkstedman ,

Just wondering if there's anything on the 1.0 roadmap I can help out with?

**Comment by rkstedman** [comment]
Hi @curran! Thanks so much for checking in! You might have a noticed a bit of activity on the repo lately -- Nate, Eric, and I have started meeting 1 hour a month to look at PRs and issues and see what progress we can make. I think we're meeting this Friday and I can surface this question to the group then!

**Comment by curran** [comment]
@rkstedman Awesome! Happy to hear of the meetings and steady dedication to the project :)

**Comment by curran** [comment]
Noticed there is now a milestone for 1.0! This is great https://github.com/share/sharedb/milestone/1

Closing this issue, as the 1.0 goals are there in the milestone.

**Comment by curran** [comment]
I'm reopening this as ShareDB has been at 1.0 Beta for over 2 years now. Just release 1.0 already please!

**Comment by curran** [comment]
FWIW when you run `npm install sharedb`, it installs `v0.11.37` from 2016.

**Comment by felixk101** [comment]
https://github.com/share/sharedb/releases/tag/v1.0.0 has been released since 2019, so this issue can be closed.
