### ISSUE TITLE
Reconnection and offline change syncing

### ISSUE THREAD

**Issue by Nickasd** [share/sharedb#151]
In the readme it is specified:

- Reconnection of document and query subscriptions
- Offline change syncing upon reconnection

Are there any other details about how the reconnection works? When I tried these features didn't seem to work. Also it would be great if one could specify the interval as an option.

**Comment by DetweilerRyan** [comment]
please see issue #121 for details.

**Comment by Nickasd** [comment]
Thanks, didn't see that one!
