### ISSUE TITLE
Collaborative Mind Map

### ISSUE THREAD

**Issue by WinMinTun** [share/sharedb#170]
Hi, I have already developed Collaborative RichText Editor with OT type 'rich-text'. Now I need to develop a Mind map editor with many collaborators editing real-time. Which OT type should I use? Is it 'json0'? Could somebody shed me some light on this? Thank you

**Comment by curran** [comment]
Do you already have a data structure in mind for the mind map? If your data structure can be represented as JSON, then probably 'json0' is the way to go.

**Comment by josephg** [comment]
You can also embed rich text operations inside the json structure if you want.
