### ISSUE TITLE
Error code documentation is out-of-date

### ISSUE THREAD

**Issue by alecgibson** [share/sharedb#198]
The error codes documented at the end of the `README` are out-of-date. For example, according to the [`README`][1], error `4002` means "Database adapter does not support subscribe". However, according to the [source code][2], error `4002` means "Op submit rejected".

I'm happy to raise a pull request to delete these from the `README` to at least reduce confusion, but probably don't have the time to rummage through the code to update the docs.

[1]: https://github.com/share/sharedb#4000---bad-request
[2]: https://github.com/share/sharedb/blob/ea5053b8064876538c61a2284c4f931fa8b52c79/lib/client/doc.js#L273

**Comment by nateps** [comment]
Thanks for flagging this!

Fixing the error codes is something I'd like to do for a 1.0 release, and this should be a relatively quick update.

As of Node.js 8.0, Node uses the convention of Error.code being a string, which in retrospect makes more sense than a number. I'd like to update both the codes in ShareDB and the README to be a unique string in a similar convention to the one used by Node.js: https://nodejs.org/api/errors.html#nodejs-error-codes

I was planning to make this change, but if you'd like to suggest some codes, I'd appreciate the help!
