### ISSUE TITLE
How to use the sharedb-string-binding with Angular?

### ISSUE THREAD

**Issue by Pineapplebun** [share/sharedb#246]
I'm having some issues implementing the textarea example in sharedb with Angular 5.

TextArea example:
https://github.com/Teamwork/sharedb/tree/master/examples/textarea

In MyComponent.component.html:

`<textarea id="test-input"></textarea>`

In MyComponent.component.ts:

```
import { Component, OnInit, ElementRef, Input } from '@angular/core';
import { SharedbService } from '../../sharedb.service';
import { ActivatedRoute } from '@angular/router';
import { Doc } from '@teamwork/sharedb/lib/client';
import * as StringBinding from 'sharedb-string-binding';

export class MyComponent implements OnInit {

  doc: Doc;
  binding: any;

  constructor(
    private route: ActivatedRoute,
    private sharedb: SharedbService,
    private el: ElementRef) { }
  
  ngOnInit() {
    const id = '1234' // for example
    this.loadDocument(id)
  }

  loadDocument(id: string) {
    this.doc = this.sharedb.get('collectionName', id);
    this.doc.subscribe((err) => {
      if (err) {
        throw err;
      }
      const element: HTMLElement = this.el.nativeElement.querySelector('#test-input');
      this.binding = new StringBinding(element, this.doc);
      this.binding.setup();
    });
  }
}
```

The console error is this:

ERROR TypeError: previous.charAt is not a function
    at StringBinding.TextDiffBinding.onInput (index.js:52)
    at HTMLTextAreaElement._inputListener (index.js:29)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4751)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at ZoneTask.invokeTask [as invoke] (zone.js:496)
    at invokeTask (zone.js:1540)
    at HTMLTextAreaElement.globalZoneAwareCallback (zone.js:1566)

Did I make a mistake in importing the StringBinding function? Or is there a compatibility issue with sharedb-string-binding and Angular? or something else...

Thanks in advance!

**Comment by Pineapplebun** [comment]
The issue was that I didn't add a path to a document field:

`this.binding = new StringBinding(element, this.doc, ['doc field']);`

**Comment by somasekhar233** [comment]
@Pineapplebun can you share the share db service written in angular. I am just going through so many blogs didn't find proper one for setting up project with sharedb in angular

Thanks in advance
