### ISSUE TITLE
How to use redis as backend, when redis db is protected with password?

### ISSUE THREAD

**Issue by dhope-nagesh** [share/sharedb#248]
if I use redis db with password. its working fine. But if I protect my redis db password its not able to create a doc in redis

**Comment by curran** [comment]
What is the difference between "use redis db with password" and "protect my redis db password"?

Do you mean there is some difference in permissions settings or something like that?

**Comment by dhope-nagesh** [comment]
@curran Issue is being resolved, there was problem with protocol(rediss://) I was using. I switched to redis:// now its working fine.

Closing this issue
