### ISSUE TITLE
Possible to drop old ops from the oplog to save space?

### ISSUE THREAD

**Issue by devongovett** [share/sharedb#25]
Is it possible to drop old operations from the oplog to free up database space after some specified timeout?  We don't really need a full history of all operations after a few days (right?), and when operations are generated for every keypress pretty much, the database can grow very fast.

I tried using a Mongo [ttl index](http://docs.mongodb.org/manual/core/index-ttl/) on the ops but that doesn't work: We get a `Missing oplog` [error](https://github.com/share/livedb/blob/master/lib/redisdriver.js#L165) from the redis driver when both redis and mongo have been cleared.  Do we only need to keep around the latest operation (or 10 say), or is there a better solution?  Thanks!

**Comment by nateps** [comment]
This should no longer be an issue as of the sharedb rewrite. It should work properly if no ops are present or only the latest ops are present and all submissions and fetches are based on versions that are recent enough.

If a client has an old doc version and the required ops are missing, an error will be returned as appropriate.
