### ISSUE TITLE
Abstract console logging

### ISSUE THREAD

**Issue by alecgibson** [share/sharedb#250]
At the moment there's a bunch of calls to `console.warn` and the like. It would be nice to abstract this a bit so that users can provide a `console`-like object when instantiating ShareDB so that we can:

  - silence the logger (useful for tests, eg when you're deliberately throwing errors)
  - forward logs on to a custom logger, or alerting service (eg Sentry, Rollbar)

I'd imagine it to look something like:

```javascript
const ShareDB = require('sharedb');

const myLogger = {
  log: () => {}, // I don't care about logs
  warn: message => Rollbar.warn(message),
  error: message => Rollbar.error(message),
};

const share = new ShareDB({
  logger: myLogger,
});
```

If a logger isn't provided, then we can just use the default of `console`. Maybe a nice bonus option would be if we pass `logger: null`, then ShareDB will silence all logs.

We could internally also call something like:

```javascript
const logger = Object.assign({}, console, myLogger);
```

This would make sure that the logger has sensible defaults of logging to console, so you'd just have to override the things you care about. For example:

```javascript
const share = new ShareDB({
  logger: {
    log: () => {},
  },
});
```

The above would suppress all calls to `console.log`, but would still log `warn`, `error`, etc. to the console.

What do people think?

**Comment by ericyhwang** [comment]
Seems reasonable. Some logging options that seem to be common in Node:

* Nate brings up the [debug](https://www.npmjs.com/package/debug) library, used in big relatively stable libraries like Express and could be switched to with a find/replace:
  * Supports namespaces for configuring log levels on a per-library basis: https://www.npmjs.com/package/debug#usage
  * Output streams can be configured on a per-namespace + per-level, or globally: https://www.npmjs.com/package/debug#output-streams
  * Logging for a namespace can be enabled/disabled dynamically in the application entry point via a call to the library, which should also work in the browser: https://www.npmjs.com/package/debug#set-dynamically
* There's also going to structured logging, though we don't need to do so now, as that'd be more work than just switching text loggers. A few options are [Bunyan](https://github.com/trentm/node-bunyan), which I've used; or [Winston](https://github.com/winstonjs/winston) and [Roarr])(https://github.com/gajus/roarr), which I haven't.

**Comment by alecgibson** [comment]
@ericyhwang @nateps I think I still have issues with `debug`. For starters, it has no concept of log levels, which means it isn't a good drop-in replacement for `console`. We could potentially install something like [`debug-levels`][1], but it isn't very widely used (15 dependents).

We could potentially use something like [`loglevel`][2]? It's a pretty bare-bones library, but it would at least enable us to set log levels. We wouldn't be able to do anything particularly clever beyond that (eg logging to a 3rd party service). But maybe that doesn't matter too much? A lot of the places we currently use `console.error` are when we [don't even bother telling the client about the error][3].

I think I'd prefer that for its simplicity over `debug`, where we have to configure dependencies of dependencies using environment variables (yuck).

[1]: https://www.npmjs.com/package/debug-levels
[2]: https://www.npmjs.com/package/loglevel
[3]: https://github.com/share/sharedb/blob/82386dbcbe453df5b95b93f4ef78af0ce6f9d1f3/lib/agent.js#L95-L98

**Comment by ericyhwang** [comment]
Makes sense re the `debug` module not supporting levels.

The `loglevel` library looks fine to me, thanks for finding it!

I'm proposing doing something like this to get a logger to replace `console`:
```
var logger = require('loglevel').getLogger('share');
```
