### ISSUE TITLE
Detailed documentation/test missing for ingestSnapshot

### ISSUE THREAD

**Issue by curran** [share/sharedb#254]
Currently there are no tests that invoke `ingestSnapshot` directly.

Such tests would be useful in documenting exactly how one could go about using `ingestSnapshot`, which is IMO not clear from the current documentation. For example, after reading "This data must include a version, snapshot and type.", I'm still not sure what to pass in exactly. I'd guess an object with properties `version`, `snapshot` and `type`, but still not sure what kinds of values would be expected.

**Comment by curran** [comment]
In particular, I had difficulty finding out how to construct a `snapshot` from a fetched ShareDB.Doc. I eventually did get it to work, and here's the solution:

```js
const doc = connection.get('examples', 'textarea');
const snapshot = {
  v: doc.version,
  data: doc.data
};
```

This may be a good example to put in the README.

**Comment by ericyhwang** [comment]
Yup, the documentation isn't as precise as it could be. The JSDoc for `ingestSnapshot` is clearer - it says it requires `v`, `data`, and `type` fields on the `snapshot` param.
https://github.com/share/sharedb/blob/v1.0.0-beta.14/lib/client/doc.js#L150

I've updated the README in https://github.com/share/sharedb/commit/a67ad42c384809eb377c9f70c7a45a7552a4be89 to clarify the format for the param.

Any additional clarifications on the documentation that you'd like?

Re the tests, `ingestSnapshot` gets covered indirectly by doc fetch/subscribe. As you say, it could be useful to have a simple test as "enforced" documentation. If you want to add one, that'd be great!

**Comment by curran** [comment]
Thanks a ton @ericyhwang for making that update!

**Comment by curran** [comment]
Closing as the update is IMO suffucient.
