### ISSUE TITLE
Support browser environment without Browserify

### ISSUE THREAD

**Issue by curran** [share/sharedb#255]
Currently some client code accesses `process.nextTick`, in [doc.js line 663](https://github.com/share/sharedb/blob/5f4bd902d5679a1fa87f7e954f1c407d18a9049d/lib/client/doc.js#L663).

This is shimmed to `setTimeout` when building with Browserify, but other build tools such as Rollup do not automatically translate `process.nextTick` to `setTimeout`.

My current workaround is to shim it myself as follows:

```js
window.process = {

  // Required for ShareDB client. 
  nextTick: callback => {
    setTimeout(callback, 0);
  }
};
```

Would a PR that changes `process.nextTick` to `setTimeout` in the original source be welcome?

I don't see any disadvantages to making this change.

**Comment by gkubisa** [comment]
`process.nextTick` in nodejs schedules a micro-task. `setTimeout` schedules a task. See https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/ for a difference between tasks and micro-tasks.

In my opinion a micro-task would be more appropriate wherever ShareDB uses `process.nextTick`, as we just want to perform an action asynchronously as soon as possible and `setTimeout` introduces unnecessary delay. So, I'd prefer if the shim was based on `MutationObserver` or `Promise`, rather than `setTimeout`.

**Comment by ericyhwang** [comment]
My comments and thoughts:

1. Should we change `process.nextTick` to `setTimeout` in the source code?
    - No, as they do different things in NodeJS.
2. Should ShareDB itself shim `process.nextTick`?
    - I haven't really thought too deeply about if Share should do it, or to leave it to the browser bundling tool.
    - One option is to recommend a shim if your bundler doesn't do it for you. Looks like browserify uses the [`process`](https://www.npmjs.com/package/process) module as a shim.

**Comment by curran** [comment]
I researched a bit more and found the following to be the implementation of `nextTick` in the Browserify bundle:

``js
process.nextTick = function (fun) {
    var args = new Array(arguments.length - 1);
    if (arguments.length > 1) {
        for (var i = 1; i < arguments.length; i++) {
            args[i - 1] = arguments[i];
        }
    }
    queue.push(new Item(fun, args));
    if (queue.length === 1 && !draining) {
        runTimeout(drainQueue);
    }
};
```

Indeed this comes from the [process module implementation](https://github.com/defunctzombie/node-process/blob/master/browser.js#L134). Good to know!

I wonder if there's any substantive difference between what users would experience using `setTimeout` vs `nextTick`. My guess is the behavior of the system would feel exactly the same. Maybe there would be a few milliseconds difference in terms of when network requests go out, but that's eclipsed by network latency anyway.

**Comment by nateps** [comment]
Per the discussion above, I do not think ShareDB should include the shim for nextTick itself. How about we add an example that includes a shim so there is something we can point to easily. We could also add a section to the readme about using various client bundlers with ShareDB.

**Comment by miking-the-viking** [comment]
For reference to this issue, Webpack 5 removed the NodeJs polyfills by default, the following solution worked for me to get the polyfill back:

https://stackoverflow.com/a/64553486/5129500

```
// webpack needs to be explicitly required
const webpack = require('webpack')

module.exports = {

/* ... rest of the config here ... */

  plugins: [
    // fix "process is not defined" error:
    // (do "npm install process" before running the build)
    new webpack.ProvidePlugin({
      process: 'process/browser',
    }),
  ]
}
```
