### ISSUE TITLE
Error: Missing oplog for <collection>  <doc>

### ISSUE THREAD

**Issue by Dignifiedquire** [share/sharedb#26]
We are seeing some errors in production that result in this nice place here: 

https://github.com/share/livedb/blob/master/lib/redisdriver.js#L157-L166

which is to quote the comment

> This is nate's awful hell error state. The oplog is basically corrupted - the snapshot database is further in the future than the oplog.

Looking into the database, this actually was the case, the version of the document inside the mongo collection was higher than the available versions in the ops db.

Does anyone have any ideas how this can happen, what to do with this case?

**Comment by nateps** [comment]
No longer applicable as of the sharedb rewrite.
