### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by dcharbonnier** [share/sharedb#260]
Share db is leaking when multiple subscriptions to the same document.
OpStream objects are not correctly released, the problem is in the agent :

```
  var previous = streams[id];
  if (previous) previous.destroy();
  streams[id] = stream;
  [...]
  stream.on('end', function() {
    [...]
    delete streams[id];
    [...]
  });
```

When there is a previous stream, we destroy it, this destroy will trigger a "end" event when we catch the event streams[id] is not anymore the expected stream and we loose a reference to an open stream so we can't clear it when the agent is destroyed.
Two possibilities :
  - `if(streamd[id] !== stream) return;` best option for me
  - `if(stream[id].open) return`

PS : maybe that was the sense of #190 and it's not a wrong usage of sharedb it's a bug.

**Comment by alecgibson** [comment]
First option seems sensible to me.
