### ISSUE TITLE
Regression introduced in 1.0.0-beta.19 [now unpublished from NPM]

### ISSUE THREAD

**Issue by zmillman** [share/sharedb#269]
`Backend.prototype._sanitizeSnapshots` was refactored with a new method signature here: https://github.com/share/sharedb/pull/263/files#diff-29d0f208724d5ac92c70f70e7e8c230eR295

Unfortunately, that method is also used in another file: https://github.com/share/sharedb/blob/76dc6deb3e07df3f8edd4e449b0bec82f74b6f24/lib/query-emitter.js#L190

This breaks any middleware that is expecting to receive a `request` param -- it will receive a string as the `request` value instead.

**Comment by ericyhwang** [comment]
Thanks for the report, I've unpublished `1.0.0-beta.19` from NPM.

The regression wasn't caught by any tests in ShareDB, so I'll look to add a test for this case.

**Comment by ericyhwang** [comment]
Note - this only applies to `'readSnapshots'` middleware for `queryPoll()` calls. So only clients that use query subscriptions _and_ use that middleware are affected.

Document fetch/subscribe should have been unaffected.

**Comment by ericyhwang** [comment]
The change has also been reverted on `master`, for the sake of any forks.

I'll leave this issue open for a few days, for visibility.

**Comment by curran** [comment]
Suggest to close this as it's been resolved.
