### ISSUE TITLE
preValidate data argument does not have name of collection in it

### ISSUE THREAD

**Issue by antonyc** [share/sharedb#27]
Hi! preValidate accepts 2 arguments, opData and data. "data" does not have document collection in it. I can already see docName, but I also need collection name. Adding the collection name looks right for me. Do you agree?
```
{
 data: '  * [] orange\n  * [] apple',
 type: 'https://wiki.ru/types/yawikitextv1',
 v: 6,
 docName: 'users',
 m: { mtime: 1406299061056, ctime: '' }
}
```
Please explain to me what is the best place in code to add collection name in "data" argument.

**Comment by nateps** [comment]
No longer applicable with sharedb rewite. Has different validation middlware
