### ISSUE TITLE
SubmitOp from server not refreshing clients

### ISSUE THREAD

**Issue by adelriosantiago** [share/sharedb#271]
I am applying a change from the server-side like this:

```
doc.fetch(() => {
    var op = [{ p: ["content"], t: "text0", o: [{ p: 0, i: "XYZ" }] }];
      doc.submitOp(op, error => {
        if (!error) {
          console.log("success");
        }
      });
  });
```

I always get a "success" and if I do a `doc.fetch()` inside the server I correctly get the text **plus** the "XYZ" at the beginning. However this change is **not** refreshed into the clients. As soon as I change the same text on one of the clients the "XYZ" disappears.

**How can I refresh clients so that everyone catches up with the submitted operation?**

**Comment by ericyhwang** [comment]
What you're doing ought to work. In the client's connection, can you turn on verbose op debugging output, to get more visibility on what's being sent back and forth?

Here's how:

```
// var connection = new ShareDB.Connection(socket);
connection.debug = true;
```

That should give you output similar to this:

```
SEND {"a":"op","c":"repos","d":"my-doc-id","v":5,"seq":1,"op":[{"p":["org"],"oi":"share"}]}
RECV {"a":"op","c":"repos","d":"my-doc-id","v":5,"src":"019e1dfe7380bca66f219720d8572fd5","seq":3,"op":[{"p":["repo"],"oi":"sharedb"}]}
RECV {"src":"eaf45d5a32243580b4f8136eef26d105","seq":1,"v":6,"a":"op","c":"repos","d":"my-doc-id"}
```

* The client's doc is at version 4, and it submits an op at version 5.
  * In the meantime, the doc already had version 5 committed, so the client's op is transformed and actually committed as version 6.
* When the server sends the reply back to the client, it first includes the actual op committed at version 5, from somebody else.
* It then includes the ack of the client's op, telling the client that it was committed as version 6.

**Comment by atomdmac** [comment]
I believe I'm seeing this same issue.  It looks like acknowledgements are being received by the client that is initiating the change but no update is received by any of the subscribers.  I can also see the store being updated on the server so it looks like transformations are happening as expected.  It's just that updates aren't being sent to clients when the change occurs.

**Comment by nateps** [comment]
If the clients are subscribed to the same doc, they should receive the ops as Eric mentioned. Not obvious what the issue would be yet. Could you please provide us a further code example if you need help still?

Thanks!

**Comment by nateps** [comment]
Hey! We're going to close this for now in case you've already resolved your issue. Please reopen if there is more we can do to help. Thanks!
