### ISSUE TITLE
Modify 'request' using middleware

### ISSUE THREAD

**Issue by yarnball** [share/sharedb#274]
Hi,

Awesome work on this project.

Basically, I am trying to modify the users' request (for security reasons) on the **server**.

This means I do not have to explicitly share the direct DB information on the client.

I have tried using the middle ware to modify the `receive` request. However, as per the `query` middleware check below- it does not use the `MODIFIED_REQUEST_NAME` assigned (it just uses the original value).

What is the correct way to modify a request?

I have attempted the following:

```
 backend.use('receive', (request, done) => {
      request = {...request, data: {...request.data, c: MODIFIED_REQUEST_NAME } }
      done()
      // done(request) did not succeed
})
```

I also tried modifying it inside the query- no luck there either- 

```
backend.use('query', (request, done) => {
          console.log('Query Request', request)
         request = { ...request, channel: MODIFIED_REQUEST_NAME, collection: MODIFIED_REQUEST_NAME, index: MODIFIED_REQUEST_NAME}
          done()
      })
```

**Comment by ericyhwang** [comment]
Hey there,

Are you trying to alias the collection name on the server - in other words, map from an externally-facing collection name to an internal collection name?

If so, you could try [using a projection](https://github.com/share/sharedb#projections):

```
backend.addProjection('external_collection_name', 'internal_collection_name', {prop1: true, prop2: true})
```

Then from any clients, you'd use `'external_collection_name'`.

A few caveats about projections:
* You have to be using the JSON0 type.
* They require that you define a whitelist of top-level fields.
* A client could in theory still guess the internal collection name. If that's a concern, you'd probably want server middleware to reject messages unless they're in a whitelist of external collection names.

**Comment by yarnball** [comment]
Thanks for that.

@ericyhwang 
`Are you trying to alias the collection name on the server - in other words, map from an externally-facing collection name to an internal collection name?`

Yes-exactly 👍 If there is a better place for doing this substitution, I'm open to that too. I do _not_ need to restrict the fields it returns.

I'm not having much luck applying your suggestion. I think I am not understanding where to apply the `addProjection` as it needs to know the query that is happening.

I have nested it within a `backend.use` as I need to know the query/collection name that is coming in.

```
      backend.use('receive', (request, done) => {
        backend.addProjection(request.data.c, '${MODIFIED_REQUEST_NAME}', { prop1: true, prop2: true })
        done()
      })
```

Could you provide a bit more advice?

**Comment by ericyhwang** [comment]
For `backend.addProjection`, you should call it at server start-up time, shortly after getting the Backend instance. Think of it as adding a static mapping from external collection name to internal collection name, with a projection down to a set of sub-fields. You can call it multiple times to add multiple mappings.

----

As an aside about the original code at the top:

```
 backend.use('receive', (request, done) => {
      request = {...request, data: {...request.data, c: MODIFIED_REQUEST_NAME } }
      done()
      // done(request) did not succeed
})
```

That won't work regardless because it's reassigning the local argument variable, which doesn't cause any effects outside of the middleware function. Also, Share currently uses Node-style callbacks, which means that if `done(err)` gets passed anything truthy, it treats it as an error.

Middleware functions can modify the request, but they have to do so in-place, e.g. `request.foo = 'bar'`. I'm not sure how exactly Share will handle live changes to the request's collection, though. The reply back to the client might use the modified collection, which could confuse the client.

**Comment by yarnball** [comment]
Thanks for that. 

I've given your advice a try, but I still have not been able to access the request to modify it. 

The docs other areas are great, but I can't seem to get a clear example of this.

Would you be able to provide an example including where to call it? 

Here is a simple sample of what I am trying to do:. 

```
        const backend = ShareDB({ db: new ShareDBMingoMemory() });

const runServer = async (ws, req) => {
  const stream = new WebSocketJSONStream(ws);
  backend.listen(stream, req);
};

const runShareDB = async app => {
  const server = http.createServer(app);
  const wss = new WebSocket.Server({ server });
  wss.on("connection", async (ws, req) => {
    runServer(ws, req);
    backend.addProjection(req.data.c, `X_${request.data.c}`, {
      prop1: true,
      prop2: true
    });
    backend.use("query", (request, done) => {
      done();
    });
  });
  server.listen(8081);
};


```

**Comment by ericyhwang** [comment]
I've been busy with work projects, so I won't really have time to write a full websocket-based example, but here's a same-process example:

```javascript
//
// Server
//
const backend = new ShareDB({ db: new ShareDBMingoMemory() });

// Add static projection, from `todos` to `todos_internal`,
// with field whitelist of `content` and `lastUpdatedAt`.
backend.addProjection('todos', 'todos_internal', {content: true, lastUpdatedAt: true});

// This middleware rejects requests if they're not against the projection name `todos`.
backend.use('receive', (request, cb) => {
    if (!request.data) {
        return cb();
    }
    if (request.data.c !== 'todos') {
        return cb(`Invalid collection ${request.data.c}`);
    }
});



//
// Client (same-process in this example, could be in a browser)
//
const connection = backend.connect();

// This doc uses the projection name:
const doc1 = connection.get('todos', 'todo-1');
doc1.create({content: 'Lorem ipsum', lastUpdatedAt: 100}, (err) => {
    if (err) { console.log('todo-1 error:', err) };
});

// This doc tries to use the backing collection but is rejected by server middleware.
const doc2 = connection.get('todos_internal', 'todo-2');
doc2.create({content: 'Lorem ipsum', lastUpdatedAt: 100}, (err) => {
    if (err) { console.log('todo-2 error:', err) };
});
```

Couple things to note:
* It registers projections and middleware on the `backend` just after constructing it. The `ws` library's server `'connection'` event occurs once for each time a client connects, so any Share middleware registered in there would get registered multiple times.
* If you're going with a collection whitelist and more than one projected collection, then you'll want to have a map with projections, and loop over the map to add projections. That way, the middleware can check for presence in the map instead of using multiple if statements.

**Comment by yarnball** [comment]
Thank you- that does make more sense now.

It seems like it is **impossible** what collection the user had requested at the `backend.addProjections` state.

However, I do keep get `Projection todo-1 already exists` whenever I refresh the client. Do I need to manually remove projects or somehow close the port when a user disconnects?

`backend.close()` did not achieve this....

**Comment by ericyhwang** [comment]
> Just one last thing- using your example I do keep get `Projection todo-1 already exists` whenever I refresh the client.

That might happen if `backend.addProjection()` is being called inside a `"connect"` event listener, since that means it'd get called every time a client connects. `backend.addProjection()` should only be called once for each projection, generally shortly after `backend = new ShareDB()`.

> TBH, I think even without addProjections- every time I refresh the browser, a "connection" gets added. Is there something obvious I'm missing?

If you refresh the browser tab, that's pretty much equivalent to a fresh page loading in, which means a new WebSocket connection. I'm not personally familiar with the WebSocket adapter, but I'd hope it'd clean connections up after a period of inactivity.

**Comment by nateps** [comment]
Closing this since there hasn't been further discussion. Let us know if there are further questions.

**Comment by yarnball** [comment]
Hi,

Thought this might be the right place to post.

What field name do i use for projections of "rich-text" fields?

I tried 'backend.addProjection... { ops: true }' which cause ShareDB to error on an invalid field projection.

**Comment by yarnball** [comment]
It doesn't look like it is supported.

I tried to modifying `backend.js` to tweak the fields behaviour. Basically I want it to say- if no fields are requested, it should return all fields.

Here is where I tried:
https://github.com/share/sharedb/blob/master/lib/backend.js#L249

```
        var projection = request.projection && request.projection.fields && request.projection
        var collection = request.projection && request.projection.target || request.collection
        backend._sanitizeOps(agent, projection, collection, id, request.ops, function(err) {
```

This failed, as the projections code still runs. It erros here, saying "area' is undefined...

https://github.com/share/sharedb/blob/master/lib/projections.js#L90

Could you provide some guidance?

**Comment by alecgibson** [comment]
Out of interest, why are you trying to project the `rich-text` type? As far as I'm aware, you should need all of the information in the document in order to do anything useful with it...?

**Comment by yarnball** [comment]
I'm kind of repurposing `projections`- really just to "alias" requests. For my purpose, it should allow all fields through.

Basically I want to be able to "hide" anyone but the server, ever knowing the real `request.collection` uid.

Did you have a suggestion?

**Comment by alecgibson** [comment]
It looks like projections are [only supported for `json0`][1]. If you wanted to add support for `rich-text`, we'd potentially need to do some thinking about how best to handle this (my instinct is to hand it off to the type).

For now, the simplest workaround I can think of is to use the fact that `json0` [can embed arbitrary subtypes][2], so you can essentially "host" a `rich-text` document inside a `json0` document, and then obfuscate your `json0` collection name. Here's a [working example][3].

[1]: https://github.com/share/sharedb/blob/d21013384b80d8b82e78106782b484777ae54fae/lib/projections.js#L12
[2]: https://github.com/ottypes/json0#subtype-operations
[3]: https://runkit.com/alecgibson/5d1b20b44eb6d40014e08677

**Comment by yarnball** [comment]
Thanks so much for this. However,applying your example I keep getting 
` Error: invalid / missing instruction in op` as a when I try posting your suggested op. 

Any suggestions?

**Comment by yarnball** [comment]
@alecgibson Hmm I'm thinking projections won't quite cut it. For my use case, I'm aliasing (using projections) on all queries, and it will get into the 10,000's very quickly....

Is there a minimal way I might simply be able to "alias" the socket? Could I pass another variable like `maskedCollection` to "backend.js"?

https://github.com/share/sharedb/blob/master/lib/backend.js#L249

Cheers

**Comment by alecgibson** [comment]
Honestly I don't know much about projections or their performance impact. Have you tried running it on a large collection? I always find the best approach for this sort of thing is to just try it.

**Comment by yarnball** [comment]
@alecgibson , I had a play with performance and there definitely feels like hit when I add projections :( I think it might be all the "snapshot" validation (which checks the fields it can related to).

I haven't succeed- but I think removing the snapshot/field validation stuff (ie passing every field back, but still masking the collection name) should lead to better performance. But I haven't been able to successfully modify the code. Any suggestions?

I was trying to simply substitute the collection name only _IF_ the projection didn't provide fields... like so:
https://github.com/share/sharedb/blob/master/lib/backend.js#L377-L378

**Comment by alecgibson** [comment]
Masking on the stream sounds like a good idea to me.

You could potentially fork Teamwork's `websocket-json-stream` (which I think the docs recommend using?), and add some server-side check above [this line][1] to replace the incoming collection name according to your mapping.

[1]: https://github.com/Teamwork/websocket-json-stream/blob/27e0ae000daafad3b452f5ddfe5e886b3f7504bc/index.js#L37

**Comment by yarnball** [comment]
> You could potentially fork Teamwork's `websocket-json-stream` (which I think the docs recommend using?), and add some server-side check above [this line](https://github.com/Teamwork/websocket-json-stream/blob/27e0ae000daafad3b452f5ddfe5e886b3f7504bc/index.js#L37) to replace the incoming collection name according to your mapping.

Thanks so much for that suggestion (apologies for my delay- wish I say it sooner!).

I have tried this suggestion, but `sharedb` returns no results. Are you sure that line if the only one I modify? is it the ".c" property I should be modifying? Would love any assistance here :) 

1. client:
```
      const ws = new ReconnectingWebSocket('ws://localhost:8088/')
      const connection = new sharedb.Connection(ws)
      const collection = connection.createSubscribeQuery('FOO', {})
      collection.on('ready', () =>console.log(collection.results))
```
2. server:
```
// server.js
const streamMasks = {in: 'FOO',out: 'FOO_HIDDEN'}
new WebSocketJSONStream(ws, streamMasks)

// websocket-json-stream lib
            const maskedSockets = value.c ? Object.assign(value, {c: maskVals.in[value.c] || value.c}) : value
            this.push(maskedSockets)
        })

        this.ws.addEventListener('close', () => {
            this.destroy()
        })
    }

```

**Comment by alecgibson** [comment]
Yes sorry, you'll also need to probably modify messages going the other way too: https://github.com/Teamwork/websocket-json-stream/blob/27e0ae000daafad3b452f5ddfe5e886b3f7504bc/index.js#L51

The `c` property is indeed the collection.

**Comment by yarnball** [comment]
@alecgibson amazing- thank you!

Lastly, any could you help on passing/handling the cookie that comes through with the request?

```
const wss = new WebSocket.Server({ server })
  server.on('upgrade', async (request, socket, head)=> {
    sessionParser(request, {}, async () => {
      const parsedReq = await xyz
      wss.handleUpgrade(request, socket, head, ws => {
        wss.emit('connection', ws, request, parsedReq)
      })
    })
  })

  wss.on('error', e =>{
    console.log('Handle ws error', e)
  })
  wss.on('connection', (ws, req, parsedReq) =>{
      const stream = new WebSocketJSONStream(ws)
      stream.on('error', e => {
        console.log('Handle share db err', e)
      })
      share.use('connect', (request, callback) => {
        if (req.user) {
          request.agent.user = req.user
        }
        // console.log(req.sessionID, request.op)
        callback()
      })
      share.listen(stream)
    } else {
      wss.close()
    }
```

**Comment by alecgibson** [comment]
Sorry, but this sounds like not an issue with ShareDB. You'll just have to debug your Websocket setup using whatever tools you normally use.
