### ISSUE TITLE
Invalid version from server. Expected: 2 Received: 1

### ISSUE THREAD

**Issue by ColinThompson1** [share/sharedb#277]
Hi

I am struggling to diagnose why I am receiving an invalid version from the server. This is all with 1 server and a 1 client. 

### On the client side

I subscribe to my pre-created document and set up handlers for the initial load and any subsequent operations.

```
this.otdoc = sharedb.get('doc', '5a66a8e3-6de2-49b9-a1de-d761abed4d6a');
this.otdoc.subscribe();
this.otdoc.on('load', this.handleDocLoad);
this.otdoc.on('op', this.handleOp)
```

each handler updates the state of my component.

I submit my operation as follows using the json1 optype:

```
const op = ['doc', 'canvas', [{r: {}}], [{i: canvas}]];
this.otdoc.submitOp(op)
```

### On the server side

I set up the connection. Pretty standard I think.

```
const stream = new WebSocketJSONStream(ws);
backend.listen(stream);
```

 and create documents separately via a REST endpoint.

````
const connection = backend.connect();
const doc = connection.get('doc', id);
doc.create(req.body, 'json1', {}, (err) => {
     if (err) throw err;
     ...
});
````

### The socket frames

The frames are as follows: 

1. Receive the init frame
2. Send for subscribe
3. Receive the same subscribe message
4. Receive subscribe message but with data and version 1
5. *At this point submit the op*
6. Send op with v1
7. Receive op with v1 (the same message)
8. Receive the ack with v1
9. *Get the invalid version error followed by a few more frames of a fetch albeit with v2*

Any help is greatly appreciated.

**Comment by ericyhwang** [comment]
One useful debugging trick is to temporarily turn on verbose message logging on the `Connection`s. It's turned on the same way whether it's a server client or a browser client:

```javascript
connection.debug = true;
const doc = connection.get('collection', 'some-id');
...
```

That'll show you the raw Share messages being sent and received by each connection. Many of the messages will have a `src` property that indicate the source of a particular message.

----

Another useful technique is to try and write a repro case entirely in Node. The `Connection` has the same API regardless of whether it's running in a browser or in Node, so you can do this to get two separate connections (clients) running entirely in Node:

```javascript
const conn1 = backend.connect();
const conn2 = backend.connect();
```

The two connections will each have their own independent local document state, subscriptions, etc.

**Comment by ColinThompson1** [comment]
Thanks for the info.

I gave it a shot my two logs are the following.

Client
```
RECV {"a":"init","protocol":1,"id":"4b128c89cefcad37d542688ed1b06dc2","type":"http://sharejs.org/types/JSONv0"}
SEND {"a":"s","c":"doc","d":"5d0e8d01-b129-47b4-884b-b26883e59961"}
RECV {"a":"s","c":"doc","d":"5d0e8d01-b129-47b4-884b-b26883e59961"}
RECV {"data":{"v":1,"data":{"doc":{"canvas":{}}},"type":"http://sharejs.org/types/JSONv1"},"a":"s","c":"doc","d":"5d0e8d01-b129-47b4-884b-b26883e59961"}
SEND {"a":"op","c":"doc","d":"5d0e8d01-b129-47b4-884b-b26883e59961","v":1,"seq":1,"op":["doc","canvas",{"r":{},"i":{"test1":"a"}}]}
RECV {"a":"op","c":"doc","d":"5d0e8d01-b129-47b4-884b-b26883e59961","v":1,"seq":1,"op":["doc","canvas",{"r":{},"i":{"test1":"a"}}]}
RECV {"src":"4b128c89cefcad37d542688ed1b06dc2","seq":1,"v":1,"a":"op","c":"doc","d":"5d0e8d01-b129-47b4-884b-b26883e59961"}
Invalid version from server. Expected: 2 Received: 1 Object
SEND {"a":"f","c":"doc","d":"5d0e8d01-b129-47b4-884b-b26883e59961","v":2}
RECV {"a":"f","c":"doc","d":"5d0e8d01-b129-47b4-884b-b26883e59961","v":2}
RECV {"a":"f","c":"doc","d":"5d0e8d01-b129-47b4-884b-b26883e59961"}

```

Server
```
SEND {"a":"op","c":"doc","d":"5d0e8d01-b129-47b4-884b-b26883e59961","v":null,"seq":4,"create":{"type":"json1","data":{"doc":{"canvas":{}}}}}
RECV {"src":"8c334dbdaeb1b29a536bbe7ed1b56d69","seq":4,"v":0,"a":"op","c":"doc","d":"5d0e8d01-b129-47b4-884b-b26883e59961"}
{"a":"s","c":"doc","d":"5d0e8d01-b129-47b4-884b-b26883e59961"}
{"a":"op","c":"doc","d":"5d0e8d01-b129-47b4-884b-b26883e59961","v":1,"seq":1,"op":["doc","canvas",{"r":{},"i":{"test1":"a"}}]}
{"a":"f","c":"doc","d":"5d0e8d01-b129-47b4-884b-b26883e59961","v":2}
```

What's interesting is the doc in mongo has the correct version (2), ie. the version which the server should have responded with.

**Comment by ColinThompson1** [comment]
Thanks a bunch!

I had the remanence of a websocket listener leftover from testing. It was echoing the messages 😭
