### ISSUE TITLE
[1.0.0] Switch error codes from numbers to strings

### ISSUE THREAD

**Issue by ericyhwang** [share/sharedb#287]
Per @nateps on https://github.com/share/sharedb/issues/198:

> Fixing the error codes is something I'd like to do for a 1.0 release, and this should be a relatively quick update.
> 
> As of Node.js 8.0, Node uses the convention of `Error.code` being a string, which in retrospect makes more sense than a number. I'd like to update both the codes in ShareDB and the README to be a unique string in a similar convention to the one used by Node.js: https://nodejs.org/api/errors.html#nodejs-error-codes
> 
> I was planning to make this change, but if you'd like to suggest some codes, I'd appreciate the help!

We'll also want to document that this is a breaking change moving from 1.0.0-beta to 1.0.0.

**Comment by alecgibson** [comment]
Do we have a checklist for things we need to do prior to an actual v1 release? Can we make sure we remove old middleware shims, too?
