### ISSUE TITLE
Automatic redis observer creation is broken

### ISSUE THREAD

**Issue by fintanf** [share/sharedb#29]
The changes made in 606eaf8 break the automatic creation of the redis observer in redisdriver.js (L52). I'm not sure why the parameter order has changed from port,host,options to options,port,host  as the options should still be the last parameter - https://github.com/mranney/node_redis#rediscreateclient. The result is that the new client resorts to using the default host and port and ignoring those in the client it is attempting to clone.

It also looks like the port, host and options are also no longer directly accessible, but are stored in client.connectionOption, so something like the below :
```javascript
this.redisObserver = redisLib.createClient(this.redis.connectionOption.port, this.redis.connectionOption.host, this.redis.options);
```

The above would break it for old versions of the redis module, but the optionalDependencies version for redis in package.json is ^0.12.1, so no backwards compatibility required?

Workaround for the moment is to create your own observer (i.e. another redis client) and pass that in:
```javascript
var observerClient = redis.createClient(...);
var driver = livedb.redisDriver(oplogDb, regularClient, observerClient);
```

**Comment by nateps** [comment]
Thanks for the submission! This should no longer be an issue with the sharedb rewrite.
