### ISSUE TITLE
Issues when scaling servers using redis-pubsub

### ISSUE THREAD

**Issue by mkoziuk** [share/sharedb#295]
I have ran into the following issue when trying to run concurrent ShareDB instances which synchronize state using the sharedb-redis-pubsub adapter. As long as changes are made on one server, the documents sync just fine. However when an edit is made on the second server the following error is thrown and states stop syncing:
```
Uncaught Error: Invalid op submitted. Op version newer than current snapshot
    at Connection.handleMessage (bundle.js:16959)
    at WebSocket.socket.onmessage (bundle.js:16912)
```

To make sure the error is not on my end, I replicated the issue using the `rich-text` example. I  modified the serve code from the example only by adding the `sharedb-redis-pubsub` as a the `pubsub` parameter when instantiating the server. Perhaps there is something else that I'm missing?

I tried to debug the sources and so far found only that the error occurs the op version is 1 higher than the snapshot version when trying to submit the change op. I'll continue debugging, but thought that I'd ask here if anyone has ever encountered a similar issue and could share any hints?

**Comment by ericyhwang** [comment]
I'm using sharedb-redis-pubsub across a lot of servers and haven't seen this issue.

One useful debugging tool is, on each client `sharedb.Connection`, set the instance's `connection.debug = true`. That will log out all the Share messages, ops included, that each client is sending or receiving.

What were the steps to repro in the rich-text example?

**Comment by mkoziuk** [comment]
Thank you for your reply @ericyhwang. 

I've made the following changes. The changes are diffed with the current master from today, so it shows the change of the websocket-json-stream - I was running based on the older version of these examples. I'll check today if changing this lib would help.

```
diff --git a/examples/rich-text/server.js b/examples/rich-text/server.js
index 486130f..d1c0c31 100644
--- a/examples/rich-text/server.js
+++ b/examples/rich-text/server.js
@@ -3,10 +3,11 @@ var express = require('express');
 var ShareDB = require('sharedb');
 var richText = require('rich-text');
 var WebSocket = require('ws');
-var WebSocketJSONStream = require('@teamwork/websocket-json-stream');
+var WebSocketJSONStream = require('websocket-json-stream');
+var redisPubSub = require('sharedb-redis-pubsub');

 ShareDB.types.register(richText.type);
-var backend = new ShareDB();
+var backend = new ShareDB({ pubsub: redisPubSub({host: '10.0.0.3'})  });
 createDoc(startServer);


diff --git a/examples/rich-text/package.json b/examples/rich-text/package.json
index 2249e29..b6c56a2 100644
--- a/examples/rich-text/package.json
+++ b/examples/rich-text/package.json
@@ -14,11 +14,12 @@
   ],
   "license": "MIT",
   "dependencies": {
     "express": "^4.14.0",
     "quill": "^1.0.0-beta.11",
     "rich-text": "^3.0.1",
     "sharedb": "^1.0.0-beta",
     "@teamwork/websocket-json-stream": "^2.0.0",
+    "sharedb-redis-pubsub": "^1.0.0-beta.1",
     "ws": "^1.1.0"
   },
   "devDependencies": {


diff --git a/examples/rich-text/client.js b/examples/rich-text/client.js
index 6854113..271b77e 100644
--- a/examples/rich-text/client.js
+++ b/examples/rich-text/client.js
@@ -3,8 +3,17 @@ var richText = require('rich-text');
 var Quill = require('quill');
 sharedb.types.register(richText.type);

+let index = '';
+if (window.location.href.indexOf('server=s1') > 0) index = 1;
+if (window.location.href.indexOf('server=s2') > 0) index = 2;
+const server = `wss://ourtestdomain.com/testws${index}/`;
+
 // Open WebSocket connection to ShareDB server
-var socket = new WebSocket('ws://' + window.location.host);
+var socket = new WebSocket(server);
 var connection = new sharedb.Connection(socket);

 // For testing reconnection
@@ -12,7 +21,7 @@ window.disconnect = function() {
   connection.close();
 };
 window.connect = function() {
-  var socket = new WebSocket('ws://' + window.location.host);
+  var socket = new WebSocket(server);
   connection.bindToSocket(socket);
 };
```

I will also enable those debug logs and I'll post them here once I have them. 
Thanks again for your help!

**Comment by mkoziuk** [comment]
So with debugging enabled and the newer websocket-json-stream package in place, I'm still having the same error. The steps to replicate were:
1) Started two clients, connected to two different servers
2) Typed '1' on client A
3) '1' appeared on both clients correctly
4) Typed '2' on client B. It appeared only on client B, and client B got the error message in it's logs

Here are the event logs from both clients:
**Client A**
```RECV {"a":"init","protocol":1,"id":"91337ab3658697d973444a624e68402d","type":"http://sharejs.org/types/JSONv0"}
SEND {"a":"s","c":"examples","d":"richtext"}
RECV {"data":{"v":1,"data":{"ops":[{"insert":"Hi!"}]},"type":"http://sharejs.org/types/rich-text/v1"},"a":"s","c":"examples","d":"richtext"}
SEND {"a":"op","c":"examples","d":"richtext","v":1,"seq":1,"op":{"ops":[{"retain":3},{"insert":"1"}]}}
RECV {"src":"91337ab3658697d973444a624e68402d","seq":1,"v":1,"a":"op","c":"examples","d":"richtext"}
```

**Client B**
```RECV {"a":"init","protocol":1,"id":"6eebff855f4382313d641e1a938be63b","type":"http://sharejs.org/types/JSONv0"}
SEND {"a":"s","c":"examples","d":"richtext"}
RECV {"data":{"v":1,"data":{"ops":[{"insert":"Hi!"}]},"type":"http://sharejs.org/types/rich-text/v1"},"a":"s","c":"examples","d":"richtext"}
RECV {"a":"op","c":"examples","d":"richtext","v":1,"src":"91337ab3658697d973444a624e68402d","seq":1,"op":{"ops":[{"retain":3},{"insert":"1"}]}}
SEND {"a":"op","c":"examples","d":"richtext","v":2,"seq":1,"op":{"ops":[{"retain":4},{"insert":"2"}]}}
RECV {"a":"op","c":"examples","d":"richtext","v":2,"seq":1,"op":{"ops":[{"retain":4},{"insert":"2"}]},"error":{"code":4011,"message":"Invalid op submitted. Op version newer than current snapshot"}}
SEND {"a":"f","c":"examples","d":"richtext","v":null}
RECV {"data":{"v":1,"data":{"ops":[{"insert":"Hi!"}]},"type":"http://sharejs.org/types/rich-text/v1"},"a":"f","c":"examples","d":"richtext"}
```

**Comment by mkoziuk** [comment]
Having done it the README way, like this: 
```  7 var redis = require('redis');
  8 var redisClient = redis.createClient({host: '10.0.0.3'});
  9 var redisPubSub = require('sharedb-redis-pubsub')(redisClient);
 10
 11 ShareDB.types.register(richText.type);
 12 var backend = new ShareDB({ pubsub: redisPubSub });```

results in the following error:
```/home/ubuntu/sharedbexample/server1/node_modules/sharedb-redis-pubsub/index.js:58
  this.client.eval(args, callback);
              ^

TypeError: this.client.eval is not a function
    at RedisPubSub._publish (/home/ubuntu/sharedbexample/server1/node_modules/sharedb-redis-pubsub/index.js:58:15)```

**Comment by ericyhwang** [comment]
The diff on the example is very useful 👍 

I think I see the problem - ShareDB isn't hooked up to a backing database, so it's falling back to its default in-memory adapter, which doesn't have any way to share DB data between different Node processes. The pub/sub messages get passed through, but the second process only has whatever in-memory data you initialized it with.

In order for multiple servers to work, they all need to run against a shared backing database. To do that, you use one of the DB adapters, like [sharedb-mongo](https://www.npmjs.com/package/sharedb-mongo) or [sharedb-postgres](https://www.npmjs.com/package/sharedb-postgres).

**Comment by mkoziuk** [comment]
Right, of course....  and that's so obvious now that you've said it. I even did at one point consider that could have been the source of the issue but somehow wrongly assumed the instances should sync their state via Redis too. 

I have now updated my test to use the PostgreSQL adapter and as you anticipated that solved the issue. 

Thank you so much for your assistance, I really appreciate it! Also - thanks a ton for this awesome project!
