### ISSUE TITLE
Documentation for doc.unsubscribe

### ISSUE THREAD

**Issue by curran** [share/sharedb#304]
The `doc.unsubscribe` is missing documentation in the README.

https://github.com/share/sharedb/blob/master/lib/client/doc.js#L411

Here's a start, from the comments:

>Unsubscribe. The data will stay around in local memory, but we'll stop receiving updates

**Comment by ericyhwang** [comment]
Good catch! @alecgibson's added it in https://github.com/share/sharedb/pull/301/commits/a2c2873ca2d52e5d711f77da356c753e034eb848, which we're aiming to merge today.

**Comment by ericyhwang** [comment]
Added in https://github.com/share/sharedb/pull/301
