### ISSUE TITLE
Integration with a front-end data store

### ISSUE THREAD

**Issue by alecgibson** [share/sharedb#307]
Does anyone have any experience integrating ShareDB with a front-end data store like [Redux](https://redux.js.org/), [Vuex](https://vuex.vuejs.org/), etc.? Especially with Quill, too?

Does anyone have any best practice recommendations, or any pitfalls they've found with trying to combine 1-way, functional state flow with an operation-based update strategy?

Of course, a perfectly valid solution is to let ShareDB and Quill exist separately outside of the data store (especially because a data store arguably introduces a *third* "source of truth"), but integrating with the store could offer some advantages:

 - **More unified view of what happened to the UI state**: in an "ideal" data store app, all mutations to the UI pass through the store, so you should be able to replay the mutations one after the other to arrive at a given state. If ShareDB is busy mutating things outside of this store, then the store only has a partial view of the series of events that mutated the UI. This could be especially weird if a `json0` object drives large parts of the UI.
- **We can increase UI rendering efficiency**: some stores are [reactive](https://vuejs.org/v2/guide/reactivity.html), and can decrease the number of times you have to recalculate expensive properties derived from data in your store.

**Comment by curran** [comment]
I've had good experience using RxJS in conjunction with React Context to deal with ShareDB documents.

I don't have an Open Source working example to show, but I can share some snippets that might be useful:

```js
import { useEffect, useMemo, useCallback } from 'react';
import { BehaviorSubject } from 'rxjs';
import { DOCUMENT_CONTENT, DOCUMENT_INFO } from '../../../constants';
import { useShareDBDoc } from './useShareDBDoc';
import { useOpStream } from './useOpStream';
import { useSubmitOp } from './useSubmitOp';

export const useViz = initialViz => {
  const vizContentDoc = useShareDBDoc(DOCUMENT_CONTENT, initialViz.id);
  const vizInfoDoc = useShareDBDoc(DOCUMENT_INFO, initialViz.id);

  // Display initial viz until realtime connection has been established.
  const viz$ = useMemo(() => new BehaviorSubject(initialViz), [initialViz]);

  const getPreviousContent = useCallback(() => viz$.getValue().content, [viz$]);
  const vizContentOp$ = useOpStream(vizContentDoc, getPreviousContent);

  const getPreviousInfo = useCallback(() => viz$.getValue().info, [viz$]);
  const vizInfoOp$ = useOpStream(vizInfoDoc, getPreviousInfo);

  // Update viz$ content.
  useEffect(() => {
    const subscription = vizContentOp$.subscribe(({ previous, next }) => {
      if (previous !== next) {
        viz$.next({
          info: viz$.getValue().info,
          content: next
        });
      }
    });
    return () => subscription.unsubscribe();
  }, [viz$, vizContentOp$]);

  // Update viz$ info.
  useEffect(() => {
    const subscription = vizInfoOp$.subscribe(({ previous, next }) => {
      if (previous !== next) {
        viz$.next({
          content: viz$.getValue().content,
          info: next
        });
      }
    });
    return () => subscription.unsubscribe();
  }, [viz$, vizInfoOp$]);

  const submitVizContentOp = useSubmitOp(vizContentDoc);
  const submitVizInfoOp = useSubmitOp(vizInfoDoc);

  return { viz$, submitVizContentOp, submitVizInfoOp, vizContentOp$ };
};
```

```js
import { useMemo, useEffect } from 'react';
import { Subject } from 'rxjs';

// Subscribes to a ShareDB document for ops,
// returns an RxJS Subject that emits values for each op.
export const useOpStream = (shareDBDoc, getPrevious) => {
  const op$ = useMemo(() => new Subject(), []);

  // Connect to ShareDB doc for realtime connection.
  useEffect(() => {
    if (!shareDBDoc) {
      return;
    }

    // Update on each change.
    const handleOp = (op, originatedLocally) => {
      const previous = getPrevious();
      const next = shareDBDoc.data;
      op$.next({ previous, next, op, originatedLocally });
    };

    shareDBDoc.on('op', handleOp);

    return () => {
      shareDBDoc.off('op', handleOp);
    };
  }, [shareDBDoc, op$, getPrevious]);

  return op$;
};
```

```js
import { useEffect, useState, useContext } from 'react';
import { ConnectionContext } from '../ConnectionContext';

export const useShareDBDoc = (collection, id) => {
  const connection = useContext(ConnectionContext);

  const [vizContentDoc, setVizContentDoc] = useState(null);

  useEffect(() => {
    if (!connection) return;

    // Clear out old doc in case id changed.
    // (don't want the user to see stale stuff).
    setVizContentDoc(null);

    const doc = connection.get(collection, id);

    // Wait until subscribe finishes before passing this out,
    // so that downstream code can assume data is present
    // and that submitOp will work.
    doc.subscribe(() => {
      setVizContentDoc(doc);
    });

    return () => {
      doc.unsubscribe();
    };
  }, [connection, collection, id]);

  return vizContentDoc;
};
```

Then, here's the fun part, when you need to use some part of the (possibly large) state inside a ShareDB doc, but not update when parts of the doc that don't concern you are updated, you can use this pattern to extract some part of the document into local React state:

```
import { useState, useEffect } from 'react';

const identity = x => x;

// A hook for extracting some nested state from a BehaviorSubject.
export const useValue = (behaviorSubject$, accessor = identity) => {
  const [value, setValue] = useState(accessor(behaviorSubject$.getValue()));
  useEffect(() => {
    const subscription = behaviorSubject$.subscribe(behaviorSubject => {
      setValue(accessor(behaviorSubject));
    });
    return () => {
      subscription.unsubscribe();
    };
  }, [behaviorSubject$, accessor]);
  return value;
};
```

For example

```js
  const { viz$ } = useContext(VizContext);
  const vizInfo = useValue(viz$, viz => viz.info);
```

I was thinking of putting together a blog post and OSS example app with this approach, but haven't done it yet. I think this approach solves a lot of the scalability problems that you'd come across if you re-render the entire app Redux-style (or stateful-context-style). Note that the context provides an RxJS stream `viz$`, which is a state container that itself never changes. So, things that consume it don't re-render on each change. They only re-render when the state they want (via `useValue`) changes.

Cheers.

**Comment by alecgibson** [comment]
Thanks for the suggestions. I'll close this to keep the issues tidy.
