### ISSUE TITLE
Op version newer errors using pubsub and rich-text

### ISSUE THREAD

**Issue by amilich** [share/sharedb#343]
Hi! I'm seeing "ShareDBError: Invalid op submitted. Op version newer than current snapshot" when using the rich-text example and pubsub. I'm able to sync the document, but after a bunch of changes, they get out of sync and I see that error.

Do you have suggestions for mitigating these synchronization errors? Would using a mongo backend help, or how could I delay the number of 'ops' submitted through the pubsub client?

**Comment by curran** [comment]
I see the same error:

>Invalid op submitted. Op version newer than current snapshot

I'm curious, did you figure out the cause?

It seems to happen after a server restart.

One theory: document versions have been incremented in ShareDB memory, but not yet persisted to Mongo? Is that a thing that can happen?
