### ISSUE TITLE
Example for creating doc with ot-text-tp2

### ISSUE THREAD

**Issue by amilich** [share/sharedb#344]
I see [ot-text-tp2](https://www.npmjs.com/package/ot-text-tp2) is one of the possible OT types.

How do you initialize a document using this OT implementation?

Have been trying `doc.create('', ot_type.type.name, callback)` but not with desired results.

**Comment by alecgibson** [comment]
Looking at [the tests][1], it looks like the type deals with arrays. Try `doc.create([], ...)` or possibly `doc.create([{i: ''}], ...)`. If that doesn't work, please provide a minimal example of what you're trying, potentially using [RunKit][2] or similar.

[1]: https://github.com/ottypes/text-tp2/blob/master/test/text-tp2.coffee
[2]: https://runkit.com/home

**Comment by amilich** [comment]
Thank you - figured it out with the 'i' insert
