### ISSUE TITLE
Remove stream from backend.listen

### ISSUE THREAD

**Issue by amilich** [share/sharedb#345]
After calling `backend.listen(stream)`, is there any way to remove `stream` from backend or replace it with another?

**Comment by alecgibson** [comment]
What exactly are you trying to achieve?

**Comment by amilich** [comment]
If I no longer want ShareDB to listen to a particular client, but I don't want to close the entire stream

**Comment by alecgibson** [comment]
So you have other non-ShareDB messages coming over the same stream?

**Comment by amilich** [comment]
Yes, was trying that out!

**Comment by alecgibson** [comment]
I don't think that's how this was designed. Pretty sure any non-ShareDB messages will cause an error in [`Agent._handleMessage`][1]

[1]: https://github.com/share/sharedb/blob/v1.1.0/lib/agent.js#L331

**Comment by amilich** [comment]
Got it, good to know. Thanks for the help.

**Comment by jinyang1994** [comment]
@alecgibson Hi, I want too remove a particular stream, but my case is i use serverless websocket connect client, then use http call sharedb server. Call sharedb server close a stream when serverless websocket is closed. Is there any great way I can do this?😊

**Comment by alecgibson** [comment]
@jinyang1994 I'm not sure I understand your setup.

**Comment by jinyang1994** [comment]
Sorry, my English is not very good, so I may not express what I mean very well.
<img width="843" alt="image" src="https://user-images.githubusercontent.com/15340367/111065090-d676e400-84f2-11eb-8481-67388692b594.png">
I use serverless([AWS Lambda](https://aws.amazon.com/lambda/?nc2=h_ql_prod_fs_lbd)) to Load-Balance my client connections, but Sharedb can't used in serverless. So I changed my setup.
Sharedb support other transports stream. I developed custom stream based on [WebSocketJSONStream](https://github.com/Teamwork/websocket-json-stream), create a stream when the serverless is first use http call Sharedb server, and the message push in the stream,  I use aws-sdk send a message to client when the Sharedb server needs send to it in the stream `_write` method, but if client close websocket connection, I don't know how can I remove a specified stream in Sharedb server

**Comment by alecgibson** [comment]
If you're re-implementing the `Stream` interface yourself, you just need to make sure you implement the appropriate [`'close'`](https://nodejs.org/api/stream.html#stream_event_close) and [`'end'`](https://nodejs.org/api/stream.html#stream_event_end) events. ShareDB will respond to these standard events and perform any necessary [cleanup](https://github.com/share/sharedb/blob/master/lib/agent.js#L351-L352).

So — if I understand your setup correctly — you'd need to:

- Listen for the Client-AWS socket closing
- Send some special HTTP request to your ShareDB server, which signifies a client disconnecting
- React to that on your ShareDB box by closing the custom `Stream` you've written

**Comment by jinyang1994** [comment]
Thanks for your answer, I think I should call `stream.destroy` or `stream.end`.
