### ISSUE TITLE
How do I send a custom error or reject document to a client

### ISSUE THREAD

**Issue by undeadfrost** [share/sharedb#348]
How do I send a custom error or reject document to a client ?

That doesn't work
```
shareDB.use('readSnapshots', (context, callback) => {
  return callback("Error: Document owner must match currently logged in user.");
});
```

**Comment by alecgibson** [comment]
Could you please expand? What about it doesn't work? What errors are you seeing? Or what errors do you expect to see and aren't seeing? Can you provide a minimal working example using something like RunKit?

**Comment by undeadfrost** [comment]
@alecgibson I hope the client receives this error message
<img width="510" alt="微信截图_20200226165532" src="https://user-images.githubusercontent.com/24819204/75328508-1c95e100-58b9-11ea-910c-95501040b85c.png">

**Comment by undeadfrost** [comment]
Use the example above:
```
backend.useMiddleware('connect', (request, callback) => {
  // Best practice to clone to prevent mutating the object after connection.
  // You may also want to consider a deep clone, depending on the shape of request.req.
  Object.assign(request.agent.custom, request.req);
  callback();
});

backend.useMiddleware('readSnapshots', (request, callback) => {
  const connectionInfo = request.agent.custom;
  const snapshots = request.snapshots;

  // Use the information provided at connection to determine if a user can access the snapshots.
  // This should also be checked when fetching and submitting ops.
  if (!userCanAccessCollection(connectionInfo, request.collection)) {
    return callback(new Error('Not allowed to access collection ' + request.collection));
  }
  // Check each snapshot individually.
  for (const snapshot of snapshots) {
    if (!userCanAccessSnapshot(connectionInfo, request.collection, snapshot)) {
      request.rejectSnapshotRead(snapshot,
        new Error('Not allowed to access snapshot in ' request.collection));
    }
  }

  callback();
});

// Here you should determine what permissions a user has, probably by reading a cookie and
// potentially making some database request to check which documents they can access, or which
// roles they have, etc. If doing this asynchronously, make sure you call backend.connect
// after the permissions have been fetched.
const connectionInfo = getUserPermissions();
// Pass info in as the second argument. This will be made available as request.req in the
// 'connection' middleware.
const connection = backend.connect(null, connectionInfo);
```
The client:
```
    doc.subscribe(error => {
      console.log('subscribe');
      if (error) {
        console.log(error);
      } else {
        setContent(doc.data);
      }
    });
```
or
```
    doc.on('error', () => {
      console.log('error');
    });
```
There is no way to live up to expectations.

**Comment by alecgibson** [comment]
Aha sorry I think this is a mistake with the docs. The syntax is `backend.use`.

See this example: https://runkit.com/alecgibson/5e5634a307e329001b795978

**Comment by undeadfrost** [comment]
I've already modified this, I now have the server-side code:
```
shareDB.use('readSnapshots', (context, callback) => {
  return callback("Error: Document owner must match currently logged in user.");
});
```
Client code:
```
  useEffect(() => {
    doc.subscribe(error => {
      if (error) {
        console.log(error);
      } else {
        console.log('success');
        setContent(doc.data);
      }
    });
  }, [setContent, doc]);

  useEffect(() => {
    doc.on('error', () => {
      console.log('error');
    });
  }, [editor, doc]);
```
This server terminal shows up when we get to readSnapshots:
<img width="928" alt="微信截图_20200226172133" src="https://user-images.githubusercontent.com/24819204/75330728-75b34400-58bc-11ea-9bb2-ec852b72bc1c.png">
But the client did not receive any error messages,there are some questions about whether I do this.

**Comment by alecgibson** [comment]
This is hard to debug without an actual working example. From the looks of your screenshot, you're potentially wrapping something in a promise, and not handling the rejection?

**Comment by undeadfrost** [comment]
I need to notify the client when I get a document error
```
shareDB.use('connect', (context, callback) => {
  const { req } = context;
  const { query: { docId } } = URL.parse(req.url, true);
  const doc = shareDBConnection.get('examples', docId);
  doc.fetch(async err => {
    if (err) throw err;
    if (doc.type === null) {
      let content = null;
      try {
        const { data: { content } } = await getContent(docId);
        doc.create(content , 'slate-ot-type', callback);
      } catch (e) {
        // Get doc error
        callback(new Error('Not allowed to access collection'));
      }
    } else {
      callback();
    }
  });
});
```
The current situation is that the client cannot receive these errors, an error was thrown only on the server side.

**Comment by alecgibson** [comment]
I'm not sure I understand. Here in this example you're actively throwing the error, which will result in an unhandled rejection error, which is exactly what you have.

**Comment by undeadfrost** [comment]
Currently, if you want to get an error on the client for processing, how can you actively send the error to the client?

**Comment by alecgibson** [comment]
The issue here is that you've sort of confused the notion of clients. In your setup, you have a backend instance `shareDB`, on which you set up middleware (`shareDB.use`).

Inside this middleware, you have access to a client `shareDBConnection`, which happens to live on the same box as your backend instance.

Your `connect` middleware is triggering your `readSnapshots` middleware with the client on your server (which calls `doc.fetch` inside your middleware). It's then throwing the error on your server. This never gets back to the client on your remote machine.

Remember: any instance of `Doc` is a client, even if it's on the same machine as your server.

It's generally a bad idea to rely on using clients in your backend middleware. For one, you can cause infinite middleware loops (eg if your `fetchSnapshots` middleware then calls `doc.fetch` inside it).

If I understand the problem you're trying to solve, then you should pretty much copy-paste the example from the `README` (minus the `useMiddleware` typos):

   - you need to use the `connect` middleware to store the current session (including cookies, and already-authenticated user information) on the `Agent`, which is available across all middleware
  - then in the `readSnapshots` middleware, you can access the `Agent`, which has your session data, and then compare the snapshot metadata against this stored session data.

**Comment by undeadfrost** [comment]
Thank you for your answer.
Yes, I found that I didn't understand the server and the client, in my current project:
1.  Connect to the shareDB.
2.  Query the document for the corresponding ID through another server interface.
3.  Documents are created if they exist, otherwise webSocket errors need to be sent, for example:
``` {"a":"s","c":"documentContent","d":"70dea49ff4494852","error":{"message":"private doc"}} ```

This is like calling doc.del(), websocket will receive 
```{"a":"op","c":"examples","d":"321","v":1,"src":"2760bf9bc2a55b59db94387a70f9c975","seq":1,"del":true} ```
What do I need to do?

**Comment by alecgibson** [comment]
Again, I'm afraid I don't understand the question. All errors should already be sent to the client. There's nothing you should need to do.

**Comment by undeadfrost** [comment]
After connecting to ShareDB:
```
shareDB.use('connect', (context, callback) => {
  const { id } = request.agent.custom;
  if ( id !== context.snapshots.id ) {
     // Documents are not accessible
     // I need to notify other users via websocket
  }  
  ...
});
```

Just like calling ``` doc.del([options][, function(err) {...}]) ``` , other clients can receive socket messages.
``` {"a":"op","c":"examples","d":"321","v":1,"src":"2760bf9bc2a55b59db94387a70f9c975","seq":1,"del":true} ```
