### ISSUE TITLE
How to use doc.del() correctly?

### ISSUE THREAD

**Issue by undeadfrost** [share/sharedb#351]
You must use doc.fetch() before using doc.del() ?
```
doc.fetch(() => {
  doc.del({ source: true }, err => {})
});
```
Is that the right way to write it?What if I want to delete the document on the server side?

**Comment by alecgibson** [comment]
Yes this is correct. `del` — like `submitOp` — requires that you've previously fetched the document.

You can call this code server-side to delete the doc.

Also note that `source` is an optional parameter.

**Comment by undeadfrost** [comment]
Thank you for your answer
