### ISSUE TITLE
Synchronous `doc.unsubscribe` leaves me subscribed

### ISSUE THREAD

**Issue by alecgibson** [share/sharedb#357]
See test case here: https://github.com/share/sharedb/commit/1a3edc926523f45660530b5329db1fe00fd2e1cc

If I call:

```javascript
doc.subscribe();
doc.unsubscribe();
```

synchronously, then I'd expect to finish unsubscribed, but I finish subscribed.

**Comment by ericyhwang** [comment]
From https://github.com/share/sharedb/pull/356:
> Ops do not have this issue since only one op (list of op components) is in-flight at once, with the rest held in pendingOps.
>
> Medium to long term, we're thinking of having doc sub/unsub locally queued too such that there's only one in-flight, which will fix the issue with the agent remaining subscribed while the client thinks it's not. Then perhaps doing the same for presence too.

**Comment by alecgibson** [comment]
Okay running into some complication around fixing this. Mostly around connection state change. This is sort of a brain dump of my thinking so far, largely for organising my own thoughts, but also open to any suggestions.

# Summary

I think it boils down to a decision between:

  - keep requests true to the order in which they were requested (a "full flush"), even if it forces the client through some transient state that doesn't match their desired subscription state
  - try to keep subscription state as "current" as possible: the client has requested a state, and that's the state we should force ourselves to be in as soon as possible, even if it means a confusing order of callbacks, and callbacks being fired with an inconsistent state to the `Doc`

The key thing is that there can only ever be **one** inflight request at a time, so that client state stays in sync with server state.

# Example scenarios

## Stable connection

1. Connection established
1. Call `subscribe()` then `unsubscribe()`

I'd expect the following sequence of events to happen:
1. Send subscription request
1. Receive subscription callback
1. Send unsubscribe request
1. Receive unsubscribe callback

## Eager client

1. Start disconnected
1. Call `subscribe()` then `unsubscribe()`
1. Establish connection

Then we could do one of the below, but which?

### Full queue flush

Process the whole queue as in the "Stable connection" scenario:

1. Send subscription request
1. Receive subscription callback
1. Send unsubscribe request
1. Receive unsubscribe callback

### Short-circuit queue flush

We want to finish unsubscribed, which we already are, because we submitted both requests before establishing a connection and having the opportunity to subscribe. So

1. Trigger subscribe callback (without bothering to send the request)
2. Trigger unsubscribe callback (again, without sending the request)

This would be the quickest way to get the client's desired state as its current state, but could have odd side-effects. For example, consider a front-end component that uses `rendered` and `destroyed` hooks:

```
mounted() {
  doc.subscribe(() => {
     // do something with doc.data, which should be ok
  });
}

destroyed() {
  // Clean up doc and subscription
  doc.destroy(() => {});
}
```

If this component is quickly mounted and destroyed without a connection being established, it will go through these steps:

1. Mounted
1. Try to subscribe
1. Destroyed
1. Try to unsubscribe
1. Subscription callback called, but no data has been loaded; callback may throw if it assumes data is available (which is normally a fine assumption in a subscription callback)
1. Unsubscribe / destroy callback called

## Fickle, eager client

1. Start disconnected
1. Call `subscribe()`, `unsubscribe()` and then `subscribe()` again
1. Establish connection

Here, we are currently unsubscribed, but we want to finish subscribed. We could do a full queue flush (again, sending and waiting for each request in the queue), or alternatively, we could try some short-circuit behaviour:

1. Trigger unsubscribe callback without sending a request, because we're currently unsubscribed (although is it weird that it fires before the first subscribe callback?)
1. Send subscribe request
1. Fire _both_ subscribe callbacks
