### ISSUE TITLE
Database connection pooling

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [share/sharedb#36]
I have been using a connection pool in combination with mongodb using [generic-pool](https://www.npmjs.org/package/generic-pool) _(The primary reason for doing this is that I am  streaming images from GridFS)._

Looking at the API it looks like I would have to instantiate livedb multiple times, is this incompatible with the `inprocessDriver`?

I am going to give livedb its own connection for now, but do you think connection pooling is something that would make sense in combination with livedb?

**Comment by nateps** [comment]
Assuming this is no longer applicable now with ShareDB rewrite.
