### ISSUE TITLE
this.bindToSocket is not a function at Object.Connection

### ISSUE THREAD

**Issue by danijar** [share/sharedb#361]
I'm trying to run the `rich-text-presence` example. The only change I've made is to separate dependencies from my main script to avoid recompilation during development:

```html
<script src="deps.js"></script>
<script src="client.js"></script>
```

I'm generating the dependency bundle using browserify, similar to the original example:

```sh
npx browserify -r reconnecting-websocket -r -r sharedb/lib/client -r rich-text -r quill -r quill-cursors -r tinycolor2 -r bson-objectid -o static/deps.js
```

However, when starting the server, the Chrome developer tools show an error in the line that [creates the ShareDB connection](https://github.com/share/sharedb/blob/b4ce94ee4c0c19cd8c4ca739c250456af08144fe/examples/rich-text-presence/client.js#L26):

```
Uncaught TypeError: this.bindToSocket is not a function
    at Object.Connection (deps.js:16937)
    at script.js:26
```

The reason I'm a bit confused about this is that ShareDB seems to contain the client code as a submodule that isn't browserified when just specifying `-r sharedb`. However, including both `-r sharedb -r sharedb/lib/client` does not change the above error.

Do you have an idea what is causing this error?

**Comment by ericyhwang** [comment]
How are you generating client.js?

Also, if you've got a fork that can reproduce the issue, even better.

`Conection#bindToSocket` is defined in the same file as the Connection constructor function, so it's very weird that the error says that "this.bindToSocket is not a function".

Might be something with browserify. I recall there's a flag that has to be passed to externalize a module, though I've never used it before myself.

**Comment by danijar** [comment]
Thanks for your quick reply! I just put together a fork that's as close as possible to the example and it does work now. Perhaps something was being cached that caused the problem.
