### ISSUE TITLE
how to pass data on client that will not conflict remote client

### ISSUE THREAD

**Issue by Zaynex** [share/sharedb#366]
Hi, I am using sharedb,and I meet a problem.
I want pass some basic data that will not conflict the remote data.

exmaple here:

client1
```
docs.submitOp(op)
// but I also want send some information, like `id`, 
// if it send send more params  it will be better

docs.submitOp(op, 'information')
```

client2
```
docs.on('op', (op, staticValue) => {
  console.log('i need information', staticValue)
})
```
But the second params is designed to source which is used to detect the op origin.
Any suggestions?  Thanks.

**Comment by alecgibson** [comment]
What's the exact use case?

**Comment by Zaynex** [comment]
> What's the exact use case?
I some texts like
```
abcd       //  -> each line has a unique id   (id1)
acbd       //  -> each line has a unique id  (id2)
nice day!  // -> each line has a unique id  (id3)
```

image my text like a hash map
```
{
 id1: 'abcd',
 id2: 'abcd',
 id3: 'nice day'
}
```

I have a  text like `abcd`, the  text has a unique id .
user1 insert '3' at index 3    (apply on id1)
user2 insert '3' at index 3    (apply on id1)

After operation-transform, user2 got the user1 operation, user1 got operation2 operation.

But in the client doesn't know which text should be apply with operation.
I need the unique id to make operation apply on right text.

**Comment by alecgibson** [comment]
I'd suggest looking into using the [`rich-text` type][1], which lets you attach metadata to text:

```js
const op1 = [
  {insert: 'abc', attributes: {author: 'user1'}},
];

doc.submitOp(op1, () => {/** wait for callback **/});

const op2 = [
  {retain: 1},
  {insert: 'd', attributes: {author: 'user2'}},
];

doc.submitOp(op2, () => {/** wait for callback **/});
``` 

Then the contents of `doc.data` will look like:

```js
[
  {insert: 'a', attributes: {author: 'user1'}},
  {insert: 'd', attributes: {author: 'user2'}},
  {insert: 'bc', attributes: {author: 'user1'}},  
]
```

Quill has [a lot more explanation][2].

[1]: https://github.com/ottypes/rich-text
[2]: https://quilljs.com/docs/delta/

**Comment by Zaynex** [comment]
Thanks,  `rich-text` seems a  good choice. It also relys on `Delta`.I need some time to undestand.

And, whether to consider adding an interface that can pass ot params and native data（business logic）?
I think many project need to write `convert function` that convert native data to `op` data.
If clients can receive both `op` data and native data, It will provide a lot of convenience.
