### ISSUE TITLE
How to submit a new value from the server?

### ISSUE THREAD

**Issue by adelriosantiago** [share/sharedb#372]
Is it possible to submit an entire new value without having to `submitOp(op)`? Like some sort of `submitValue(new_value)`?

Otherwise, what impact does it have to `create` the document again?

**Comment by alecgibson** [comment]
Hi @adelriosantiago I'm not sure I understand your question. Can you please provide some example code? If you're trying to clear a document, the simplest way to do it is probably to use `doc.del`, and then you can recreate it with `doc.create`

**Comment by curran** [comment]
If you want to replace something old with something new, you can pass in the old and new things into https://www.npmjs.com/package/json0-ot-diff , which can compute the diffs for you and generate the ops you need to change the old thing to be the new thing.

**Comment by adelriosantiago** [comment]
Sounds what I'm looking for @curran. The purpose is to "ban" certain words so that `hello bad_word world` would be replaced to `hello world` from the server. I will try to use that in combination with an `afterWrite` middleware.
