### ISSUE TITLE
Composing the last pending Op and the submitted Op can result in `null`

### ISSUE THREAD

**Issue by antoinelyset** [share/sharedb#373]
Hi!

While testing ShareDB with the JSON1 OT, I encountered an interesting bug. When we compose the last pending Op and the submitted Op before sending it to the server, it can result in `null` (with JSON1 at least).

https://github.com/share/sharedb/blob/cea06f8b2e6a4553eda9146782cddd24481f71dd/lib/client/doc.js#L808-L813

This raises a lot of different problems and crashes because `op.op` is falsy.

We don't send the actual Op (`null`) see :
https://github.com/share/sharedb/blob/cea06f8b2e6a4553eda9146782cddd24481f71dd/lib/client/connection.js#L455-L463

Here we return `undefined`: 

https://github.com/share/sharedb/blob/cea06f8b2e6a4553eda9146782cddd24481f71dd/lib/agent.js#L824-L833

And maybe more.

I have the resources to fix this bug but I wanted to know your opinion on how to fix it first.

Should we prevent sending it client-side? If yes, how can we express a value as skippable? (Should it be defined type-wise? Should it be a definable function called before sending the value?)

Should we just send `null` as a regular value and modify every call site to something like `if (op.op !== undefined) `?

Thanks for reading me.

**Comment by alecgibson** [comment]
I haven't personally touched much of the OT stuff, but my first thought is that if we don't already handle this case, then a falsy return from `type.compose` is invalid, and should be fixed in the `json1` library. The [docs](https://github.com/ottypes/docs#optional-properties) aren't particularly thorough, but they do mention this of `type.compose`:

> compose(op1, op2) -> op: (optional) Compose op1 and op2 to produce a new operation

I don't think it's crazy to assume that `compose` should always return a valid op (even in the event of a no-op).

That being said, I _also_ don't think it's crazy to handle a `null` no-op. I'd start with raising this in the `json1` library, and checking that a `null` return from `compose` is expected.

@josephg maintains both `json1` and the `docs` libraries, so might have more insights?

**Comment by curran** [comment]
It would be interesting to put together some unit tests for this case for both `json1` (your failing case) and the equivalent ops in `json0`.

**Comment by antoinelyset** [comment]
I don't know if it's only related to `json1`, we could imagine a compose that returns `false` or `[]`.

Let's wait for @josephg answer then.

**Comment by josephg** [comment]
Yeah in json1, noop is represented as `null`. There’s lots of compositions and transforms which generate a noop - like inserting some content then deleting it again. Or transform when both users make the same edit. 

If null is currently an invalid value for an operation in sharedb, my preference is to consider that a bug in sharedb and make it cope with nulls. The actual operation value should be opaque to sharedb anyway.

If you want a sentinal value for sharedb, undefined might still be ok (or a missing key or some equivalent).

**Comment by alecgibson** [comment]
Okay, this sounds relatively sensible to me. I'll raise it for discussion at the ShareDB PR meeting tomorrow.

@josephg are there more thorough OT API docs lying around somewhere? If not, we should probably update the existing docs to state that `null` is a valid return type. Of just `compose`? Or can we return `null` from other methods, too? We should also consider some approach to versioning the OT type API. I think I'd have considered returning `null` a breaking change in the API (given that no other types do that).

**Comment by josephg** [comment]
Sadly not - that would be a good document to write. 

And yes, other functions can return null. Anywhere a function should return noop, nulls will pop out. I wonder if a different sentinal value would have been more convenient - like `[]` or something. It’s specialcased everywhere in json1 anyway.

**Comment by curran** [comment]
`[]` seems sensible. I think that's a noop in JSON0.

**Comment by josephg** [comment]
It is. It’s a breaking change at this point though, so ideally I’d prefer not to change it in json1.

**Comment by curran** [comment]
Agreed - this highlights some assumptions that ShareDB makes, which are not necessarily valid.

Seems like it might be straightforward enough to special case for `null` in ShareDB? Meaning, in certain places, replace `null` with `[]` in the ShareDB side? Could be a wrapper like `nullGuard(op)` that could be dropped in here and there.

**Comment by curran** [comment]
@antoinelyset Do you happen to have an example setup where we could reproduce this crash?

**Comment by antoinelyset** [comment]
I don't have a simple example at hand right now, but I can try to create one. Do you have a starting repository? It's basically :

```javascript
doc.submitOp(json1.insertOp([0], 'Hi'))
// Have some delay here to have the next ops pending
doc.submitOp(json1.insertOp([1], 'Hi'))
doc.submitOp(json1.removeOp([1]))
```
The composition of the 2 last ops returns `null` with JSON1.

```javascript
json1.type.compose(json1.insertOp([1], 'Hi'), json1.removeOp([1]))
// => null
```

For the fix, I don't think we should have a special case for `null` or replace it by `[]`. We should just assume that if there is an `op` key in the `op` object, it means it's an operation, not a creation nor a deletion.

In the code I linked, we do a `if (op.op)` so it would fail for `false` or even `[]` as value.

**Comment by alecgibson** [comment]
Okay, @antoinelyset I've had a chat with @ericyhwang :

- Let's allow the shape `{op: null}` everywhere in the code, including server-side
- Update `Doc`'s [concept of a no-op](https://github.com/share/sharedb/blob/5581406ed92db5220e85b9ccb99bc25ef66b608f/lib/client/doc.js#L506-L510) to match this new shape
- You'll need to look at [`ot.js`](https://github.com/share/sharedb/blob/5581406ed92db5220e85b9ccb99bc25ef66b608f/lib/ot.js) and ensure that any calls to `type.<function>` can handle a nully no-op
- When testing you may want to particularly consider [`SubmitRequest`](https://github.com/share/sharedb/blob/5581406ed92db5220e85b9ccb99bc25ef66b608f/lib/submit-request.js), which calls `transform` (so could in theory generate a no-op server-side)

**Comment by ericyhwang** [comment]
Generally, best way to repro is to write a test case. I'd recommend copying one or more of the submit.js tests into a new submit-json1.js file:

https://github.com/share/sharedb/blob/cea06f8b2e6a4553eda9146782cddd24481f71dd/test/client/submit.js#L121

Be sure to add a `types.register` for json1! We're ok with adding `ot-json1` as a `devDependency` to sharedb.

**Comment by antoinelyset** [comment]
Fixed! Thanks for everything
