### ISSUE TITLE
Invalid op submitted error

### ISSUE THREAD

**Issue by RisingGeek** [share/sharedb#377]
For 7-8 minutes of active session, everything works fine. After That, I get this warning:
`WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.`
Then, If I try to submit op, I get the following error:
`Uncaught Error: Invalid op submitted. Op version newer than current snapshot` 
I am not sure whether this is a problem related to sharedb or websocket.

**Comment by alecgibson** [comment]
I think this has come up before: https://github.com/share/sharedb/issues/275

**Comment by RisingGeek** [comment]
Got It.
