### ISSUE TITLE
Problem registering JSON1 ottype

### ISSUE THREAD

**Issue by marcusnewton** [share/sharedb#383]
I tried using JSON1 based on the example from https://github.com/share/sharedb/pull/382 but I get a `ShareDBError: Unknown type`

```js
import ReconnectingWebSocket from "reconnecting-websocket";
import ShareDB from "sharedb/lib/client";
import json1 from "ot-json1";

const ws = new ReconnectingWebSocket(WS_URL);
ShareDB.types.register(json1.type); // ShareDBError: Unknown type
const connection = new ShareDB.Connection(ws);
```

Tested with `"sharedb": "^1.3.4"` and `"sharedb": "^1.0.0-beta"` which @eMarek was using

**Comment by alecgibson** [comment]
You'll also need to register the type on the server.

**Comment by marcusnewton** [comment]
Awesome, thanks, it works.
