### ISSUE TITLE
Add support for JSONv1

### ISSUE THREAD

**Issue by sionzeecz** [share/sharedb#388]
Hello! I'm migrating my project from JSONv0 to JSONv1 and found an interesting issue.
I'm using JSONv1 tools for operations, eg. `editOp`, `moveOp`, etc...

Today I have created operation:

```typescript
const op = JSON1.editOp(["blog", "articles", 0, "text"], "rich-text", delta);
```

and send it through sharedb:

```typescript
this.#document.submitOp(op)
// or
this.#document.submitOp([op]) // no difference
```

on OP event I'm receiving `["blog", "articles", 0, "text", {et: "rich-text", e: Delta}], true`

---
The second user who is listening to `OP` is receiving:
1 call: ["blog"], false
2 call: ["articles"], false
3 call: [0], false
4 call: ["text"], false
5 call: [{et: "rich-text", e: Delta}], false

The code for _otApply separated the array into chunks and thinks the content are individual ops.
The message what second user received is:

```json
a: "op"
c: "documents"
d: "9845564"
op: (4) ["blog", "articles", 0, "text", {et: "rich-text", e: Delta}]
seq: 2
src: "fb07ab402aa220125f857cd0b5937bda"
v: 3
```
---
Is this issue related to how JSON1 is packing operations or to how is ShareDB handling them?

**Comment by josephg** [comment]
At a glance it looks like a sharedb bug. I haven't tested rich text through json1's embedded types. It should work, but there might be a bug around serialization (since rich text uses an internal format).

**Comment by sionzeecz** [comment]
@josephg I have just tried sending simple OP change:

```
const op = JSON1.editOp(["test"], "A", "B")
```
and second side received 
["test"] and then {r: "A", i: "B"}

Seems it is not related to rich-text.

**Comment by alecgibson** [comment]
Can you please provide a minimal reproduction of the error? Or if you think you've found the problem, a pull request with a new test case is always welcome!

**Comment by sionzeecz** [comment]
I will make minimal reproduction later. :+1: 

Anyway I'm not able to repair the issue in proper-way. 
My workaround is more like "hack" than a solution.

I can imagine the right way is to somehow identify the message about having path and not multiple operations.
But it will require to modify all ot-types which is huge breaking-change. _(or some dirty change)_

for example the `JSON1.replaceOp(["test"], "A", "B")` should tell the sharedb if it is array of operations or array of paths and put this information into message what is send through websocket.

A way could be changing `a` property to `op` if array is path and to `ops` if array is list of operations.

single operation:
```
{ a: "op" c: "documents" d: "9845565" op: ["test", {r: "A", i: "B"}] }
```

multiple operations:
```
{ a: "ops" c: "documents" d: "9845565" op: [ ["test", {r: "A", i: "B"}] ], ["test2", {r: "A", i: "B"}] ] }
```

**Comment by alecgibson** [comment]
Shouldn't the above check only apply to `json0`? Unless you've changed your `defaultType`...?

**Comment by sionzeecz** [comment]
You are right! I accidentally replaced json0 with json1 and haven't realize it can do these issues. 
Thank you and sorry for messing it up. Feel free to close it.

**Comment by alecgibson** [comment]
Yeah sorry about that. It'd be nice to make `defaultType` properly configurable at some point, but at the moment you can't really change it without breaking a bunch of stuff.

**Comment by sionzeecz** [comment]
btw I did a quick research and found there is just one part related to JSON0.
https://github.com/share/sharedb/blob/5218767d78ee72a4ff92ecd483e9e8bdd23e9ffc/lib/client/doc.js#L594

So fix is changing defaultType to:
```typescript
if (!source && this.type.name === "json0" && op.op.length > 1) {
```

I think it will not be still compatible with projections but this change is making sense to me. The code is there specially for JSON0 so maybe worth to change it to explicit check for JSON0 type?

**Comment by curran** [comment]
It's amazing to see JSON1 getting more traction!
