### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by wukaMM** [share/sharedb#393]
Hi, thank you for the great job!

I'm using quill with sharedb, it works fine if I input some words or upload some images. But I have several blot in my quill, and if I send a blot structure, I will get the error below:

![image](https://user-images.githubusercontent.com/1595115/93840866-6cf4e600-fcc4-11ea-9bb7-6bc2abca9c0d.png)

And here is my code( same with the example 'rich-text'):

![image](https://user-images.githubusercontent.com/1595115/93840887-80a04c80-fcc4-11ea-9562-d0ae23d4a5b1.png)

Should I serialize the delta before submit? and how to?

Looking forward to your reply, thank you.

**Comment by alecgibson** [comment]
You're passing the `quill` object as a `source`, when the `source` should be a string. I think you meant:

```js
doc.submitOp(delta, {source: 'quill'});
```

**Comment by wukaMM** [comment]
Thank you for your reply.

Changing quill to 'quill' doesn't work for me, I've found another way to solve it.

Thank you again, nice day~
