### ISSUE TITLE
how to use unsubscribe

### ISSUE THREAD

**Issue by wukaMM** [share/sharedb#394]
Hi,

I used sharedb in this way,

Created a doc first, and then, when a user click the 'share' button on my website, these code will run:

```
    const doc = connection.get('connection', ' id');
    const quill = this.myEditor;

    doc.subscribe((err) => {
      if (err) throw err;
      quill.setContents(doc.data);

      quill.on('text-change', (delta, oldDelta, source) => {
          ....
      })

     doc.on('op', (delta, source) => {
         ...
     })

   })
```

It works fine if a user only click the button once, but if the button was clicked by a user twice, the content which shared to quill would be duplicate. for example, put in 'f', would become 'ff'. And also, if the button was clicked by a user three times, 'f', would become 'fff'.

I think I should use doc.unsubscribe, and I used this before the button was clicked:

```
   const doc = connection.get('connection', ' id');

    doc.fetch(() => {
      doc.unsubscribe(() => {
        ...
      });
    })
```

But it didn't work, how to use the unsubscribe correctly?

Looking forward to your relay. Thank you.

**Comment by alecgibson** [comment]
It's hard to say, because you've omitted the code that actually updates Quill, but I suspect you're either:

- updating Quill with the entirety of the new document (instead of the partial update); or
- not ignoring local ops (those with a truthy `source`) in `doc.on('op')`

I'd start by copying the [Quill example][1] and tweaking to suit your needs. In particular pay attention to the `source` checks in both `doc.on('op')` and `quill.on('text-change')`.

[1]: https://github.com/share/sharedb/blob/master/examples/rich-text/client.js

**Comment by wukaMM** [comment]
Thank you for your answer, and I'm sorry for didn't paste the code completely.

The code in doc.on('op') is

```
  doc.on('op', function(op, source) {
    if (source === quill) return;
    quill.updateContents(op);
  });
```
and the code in quill.on('text-change') is 

```
  quill.on('text-change', function(delta, oldDelta, source) {
    if (source !== 'user') return;
    doc.submitOp(delta, {source: quill});
  });
```
both as the quill example does.

I'd like to describe my scenario again, two users are on my website with one document, the first user subscribes to the document all the time, but the second one, I want him to unsubscribe and then subscribe, and then unsubscribe, and then subscribe, after this, when the first user types 'f', the second user will get 'ff'.

And I checked the source in doc.on('op') and quill.on('text-change'), it's correct, but when the first user types one chat, the callback of doc.on('op') of the second user will be caused twice. I think this is the problem which is bothering me. And in my scenario, I can't always create a new document, sometimes I need the old one.

Looking forward to your relay. Thank you.

**Comment by alecgibson** [comment]
I'm not sure I understand what you're trying to achieve. Can you please post a clear, step-by-step explanation of your desired effect, or — better yet — a minimally working example of your issue.

**Comment by wukaMM** [comment]
Thank you for your reply.

Here is my code. (Almost the same with the Quill example)

```
createDoc = () => {
    const doc = connection.get('collection', 'id');

    doc.fetch((err) => {
      if (err) throw err;
      if (doc.type === null) {
        const quill = this.myEditor;
        doc.create(quill.getContents(), 'rich-text');
      }
    });
};


unsubscribeDoc = () => {
    const doc = connection.get('collection', 'id');
    doc.fetch(() => {
      doc.unsubscribe();
    })
}

subscribeDoc = () => {
    const doc = connection.get('collection', 'id');
    const quill = this.myEditor;

    doc.subscribe((err) => {
      if (err) throw err;
      quill.setContents(doc.data);

      quill.on('text-change', (delta, oldDelta, source) => {
        if (source !== 'user') return;
        doc.submitOp(delta, {source: quill});
      });

      doc.on('op', (delta, source) => {
        if (source === quill) return;
        quill.updateContents(delta);
      });
    });
}
```

And here is my steps.

```
Step 1:
	User A:
		createDoc()
		subscribeDoc()
Step 2:
	User B:
		subscribeDoc()
		unsubscribeDoc()
		subscribeDoc()

Step 3:
    User A:
        types a chat 'f' in his quill

Step 4:
    User B: 
    	will get 'ff' in his quill, but I expect just one 'f'

```

Because of the callback of doc.on('op') was called twice. So I think the function 'unsubscribeDoc' doesn't work. And I'd like to know how to unsubscribe the doc correctly.

Looking forward to your relay. Thank you.

**Comment by alecgibson** [comment]
I'm not sure I understand exactly what you're trying to achieve here: this setup is quite unusual (why are you subscribing, and unsubscribing, and why fetch before unsubscribing, etc.?). I think your immediate problem of duplicate content is because every time you call `subscribeDoc`, you're registering a new `quill.on('text-change')` listener, but you don't _unregister_ it in `unsubscribeDoc`. I suspect if you performed a third `subscribeDoc`, you'd get `fff` printed.

**Comment by wukaMM** [comment]
Yes! You're right, you've inspired me, I did't remove the quill.on('text-change') listener.😔
I'm very appreciate your help. Thank you very much. Have a nice day.
