### ISSUE TITLE
Cannot require livedb

### ISSUE THREAD

**Issue by mrluc** [share/sharedb#4]
This fails:

    $ npm install livedb
    $ node
    > require('livedb')
    Error: Cannot find module 'livedb'

I can confirm that livedb is in node_modules under that name, and has a package.json that also uses that name.

Compare with livedb-mongo,

    $ npm install livedb-mongo
    $ node
    > require('livedb-mongo')
    { [Function] LiveDbMongo: [Function: LiveDbMongo] }

Which works just fine.

**Comment by nateps** [comment]
No longer applicable after the sharedb rewrite.
