### ISSUE TITLE
Is it true that one redis cluster for pubsub cannot be used by more than one sharedb service?

### ISSUE THREAD

**Issue by happy15** [share/sharedb#420]
Hi there, we have multiple deployments of same app built on top of sharedb, say 2 deployments A and B, each with 3 sharedb nodes.

From what I understand, channel = collection_id + doc_id and agent only needs collection and id to send op, there is no information regarding which deployment in the pubsub message, thus one redis cluster for pubsub cannot be used by more than one deployment. 

Am I right?

**Comment by happy15** [comment]
it seems setting prefix when constructing pubsub will solve the problem mentioned above and make one redis cluster to be able to serve multiple deployments, right?

**Comment by ericyhwang** [comment]
Yes, it's a limitation of Redis's pub/sub implementation that a Redis cluster has just one set of pub/sub channels, unlike with logical DBs.

So like you've stated, you'll either want to:
1. Use a different Redis cluster for each app's pub/sub
2. Or add a prefix when constructing the sharedb `PubSub`.

My team does option #2 with staging environments that all share a Redis cluster, and it works well for us.

**Comment by happy15** [comment]
Thanks for the reply and confirmation.

We also did it the prefix way and it works like a charm.
