### ISSUE TITLE
How to listen to client disconnects?

### ISSUE THREAD

**Issue by danijar** [share/sharedb#424]
There is a middleware for listening to new connections but I didn't find any to listen to the event of closed or lost websocket connections.

We would like to use this in a custom presence implementation that stores a dictionary of information about the currently connected users in the document. Users should be removed from the dictionary when they disconnect.

**Comment by alecgibson** [comment]
Why not use ShareDB's built-in presence?

**Comment by danijar** [comment]
It doesn't support JSON docs and the idea of transformPresence seemed overly complicated to us. We show cursors of other users as CodeMirror bookmarks so they already flow with the text without need for manual transformation. Wouldn't listening to disconnects be a more generally useful feature as well?

**Comment by alecgibson** [comment]
```js
const connectedIds = new Set();
const presence = shareDb.getPresence('my-channel');

presence.on('receive', (presenceId, payload) => {
  // payload will be the arbitrary metadata you sent (see below)
  // payload will be null if the remote presence has been disconnected or destroyed
});

const localPresence = presence.create('some-presence-id');
localPresence.submit({
  // Whatever arbitrary metadata you want to send
});
```

**Comment by danijar** [comment]
Cool, we were looking into using the doc presence objects earlier but it seems we can just use the normal presence feature and use the doc UUID as channel name.

- Do I understand correctly that your example code all goes into the client and there are no changes needed to the server code?
- Is the presence object only for receiving and the local presence object only for sending, and if so, what's the reason for splitting the functionality into two separate objects?

**Comment by danijar** [comment]
Thanks! We switched to the ShareDB presence functionality by using the doc UUID as channel name. The cursors are moving much faster now. The only remaining problem is that the presence information is shared faster than the document edits, so the client inserts the new cursor position in the old version of the text. The next text arrives after that and is inserted to the right of the cursor, so CodeMirror does not move the cursor to the end of the text. Is this the type of problem that the rich-text presence transformation solves? If so, is there a simple way for us to use that feature?

**Comment by alecgibson** [comment]
> Is this the type of problem that the rich-text presence transformation solves?

Yes, this is exactly the problem that `DocPresence` solves.

> is there a simple way for us to use that feature?

The "simplest" way is obviously to use the `rich-text` type, although I appreciate that that's not a very practical answer. Sadly we don't yet have a `text0` implementation yet, so you'd have to roll your own — Pull Requests are always welcome!

You can probably reuse most of the code from `rich-text`, which is split across the [`quill-delta`][1] and [`rich-text`][2] libraries.

If you can get it working for `text0`, then we can probably adapt the code @curran pasted [here][3] to apply to `json0` sub-types.

[1]: https://github.com/quilljs/delta/blob/ddda3bf088cda3ec03d5dbcc1179679d147f3a02/src/Delta.ts#L434-L452
[2]: https://github.com/ottypes/rich-text/blob/b53cd97690804e544370423ce27c6d852abb2c7f/lib/type.js#L55-L68
[3]: https://github.com/share/sharedb/issues/423#issuecomment-753472267

**Comment by danijar** [comment]
Thanks again! We don't have the capacity and knowledge to implement that feature at the moment unfortunately.

For now, we approximately fixed the off by one cursors by re-sending the presence again with 1 second delay after every cursor activity. While a collaborator is typing, their cursor is sometimes off by one but after one second it will at least land in the correct spot.

It would be great to have doc presence support for string fields of `json0` types in ShareDB in the future and then switch to that.

**Comment by curran** [comment]
It's good to know there's demand for presence in JSON0. I hope to take a crack at implementing it!

Tracked also in https://github.com/ottypes/json0/issues/30
