### ISSUE TITLE
[Question] Best approach to communicate with another web server

### ISSUE THREAD

**Issue by nadavhames** [share/sharedb#439]
For a google docs-like web app, I am thinking of having 2 servers: 1 running shareDB, and another node express server for all the usual web app things that go on.

Ideally, I'd like... 
1. The user to directly connect to sharedb server from the browser via WS, but only to view/edit docs they have access to. 
2. The web server to be the authority that creates, deletes, and manages documents. 
        - The web server can then maintain its own separate dataset(s) recording which users own/have access to which documents, etc. This maintains separation of concerns between the web app's and sharedb's data/logic.
 
I think I understand 1. and I know auth can be done with middleware (by sending REST calls to the web server?).  
For 2, how can I communicate from web server to shareDB server and get a response back? Have the web server be a sharedb client in a WS connection? Is there a more REST-like way? 

A third idea: If document creation/deletion/management has to be performed by the browser client, my web server can give permission by auth middleware to the user to create a doc and then be notified again by middleware when it is created with object metadata to maintain its dataset?  - The web server takes on a purely reactionary gatekeeper role here instead of it being the active manager which is less ideal.

Would one of these approaches work best? Or is there a better architecture for my situation? I am pretty new to shareDB so I might have got some ideas wrong about how it works.

Any help would be appreciated!

**Comment by ericyhwang** [comment]
> For 2, how can I communicate from web server to shareDB server and get a response back? Have the web server be a sharedb client in a WS connection? Is there a more REST-like way?

Yes, having the web server use a sharedb client could work.

Alternatively, if you only need to do fetches of sharedb data from the web server, you could also query the backing DB (Mongo, Postgres, etc.) directly using the backing DB's driver. You must not do writes directly to the backing DB, but reads are fine as long as you don't need the real-time subscriptions. It also means reads would not go through any sharedb middleware like access control, so keep that in mind.

**Comment by nadavhames** [comment]
Thanks for the help - makes sense
