### ISSUE TITLE
register rich-text in ot.js

### ISSUE THREAD

**Issue by Bryan-Turek** [share/sharedb#44]
if rich-text is stable in livedb: this will be useful as I'm working on a project that connects directly to livedb from a quilljs editor.

```
registerType('rich-text');
```

and in rich-text (index.js):

```
module.exports.type = require('./lib/type');
```

**Comment by pedrosanta** [comment]
Just to leave the reference to the PR #47.

**Comment by alecgibson** [comment]
This is a configuration concern. Closing.
