### ISSUE TITLE
Make `Agent` required or optional in `Backend` methods

### ISSUE THREAD

**Issue by alecgibson** [share/sharedb#454]
Most of the `Backend` methods have `agent` listed as their first argument. For example, [`Backend.submit()`](https://github.com/share/sharedb/blob/b4a2add61d1fda8db912003431534071cbb7f195/lib/backend.js#L208):

```js
Backend.prototype.submit = function(agent, index, id, op, options, originalCallback) {}
```

Normally, the first argument would be considered required (with optional arguments being at the end). However, we sort of "unofficially" support omission of the `agent` argument (its only use is being passed into middleware). This is exercised in a lot of tests by passing a `null` agent, but has also now led to the need to [check for falsiness](https://github.com/share/sharedb/pull/446/files#diff-7817c72769c3bf91926976c4c92e99c6e5c38d7e38ed3b3db59af717a2b09c95R395), which is surprising for the first argument.

We should either:

- Treat `Agent` as required: remove these checks, and update our tests to always pass in an `Agent` (or a mock)
- Move `agent` towards the end of the arguments and treat it as optional

Note that treating the `Agent` as optional may have the added benefit of making the `Backend` methods a bit more "user-friendly", so that consumers don't have to spin up an `Agent` instance to use these methods directly.

The flip-side is obviously that this may compromise middlewares that expect an `Agent` to be present (maybe omitting `Agent` could have the side-effect of bypassing middleware? This could potentially be useful for accessing `Backend` methods from within middleware itself, and avoiding infinite middleware recursions, which I've certain run into in the past).

**Comment by ericyhwang** [comment]
After discussion between Alec, Christina, and me, the decision is to make the `Agent` required in at least all the `Backend` methods for which it's the first parameter.

If we do want to have some way of skipping middleware in the future, we said that it'd be better to have some sort of flag on a separate `Backend` instance to do so, as that's less "magic" than checking for the absence of `Agent`.
