### ISSUE TITLE
Limit published files

### ISSUE THREAD

**Issue by pypmannetjies** [share/sharedb#459]
We are not currently making use of the package.json files property, it would be good to add it to reduce the package size.

**Comment by alecgibson** [comment]
We should probably just [`.npmignore`](https://docs.npmjs.com/cli/v7/using-npm/developers#keeping-files-out-of-your-package) everything by default, and then _unignore_ `lib`.

**Comment by pypmannetjies** [comment]
> We should probably just [`.npmignore`](https://docs.npmjs.com/cli/v7/using-npm/developers#keeping-files-out-of-your-package) everything by default, and then _unignore_ `lib`.

What is the benefit of doing that over just including only `lib`?

**Comment by alecgibson** [comment]
Aha sorry I skimmed your comment; I've only ever used `.npmignore`. Using `files` makes way more sense.
