### ISSUE TITLE
Add metadata to a project data, not ops?

### ISSUE THREAD

**Issue by noahdavis319** [share/sharedb#465]
Is it possible to add metadata to a projects, not necessarily to each operation?

For example, I am using MongoDB and while I currently store the `userID` of who made what changes in each `op` based on a previously asked issue here by another user, I also want to store a unique value (separate from the `_id`) to each documents. I want this because my application has multiple documents associated with each "project". Instead of tracking which ShareDB documents belong to which project using another collection, I'd like to store the ID of the "project" as a metadata value in each ShareDB document.

This request adds the equivalent of the existing `m` field from `o_project_data` to `project_data`, or extends the ability to add additional parameters under the existing `_m` key. These additional metadata value only need to be added in when a ShareDB document is created, however being able to access it and add/modify to the metadata after the fact would be helpful too.

**Comment by alecgibson** [comment]
You should be able to update the document itself in the [`commit`](https://share.github.io/sharedb/middleware/#commit) middleware hook.

**Comment by noahdavis319** [comment]
Thanks @alecgibson , is the version of the document stored in `project_data` referred to as a Snapshot? Can you point me to where in the documentation I can learn more about how the databases are utilized/configured, if that exists?

Would something like this work? I cannot test currently.

`backend.use('commit', (request, callback) => {
    request.op._m.my_custom_field = 'hello';
    callback();
});`

**Comment by alecgibson** [comment]
In the middleware:

 - `op` is the diff that you've submitted (saved in `o_project_data`)
 - `snapshot` is the document itself (saved in `project_data`)

I still need to write some documentation around the op lifecycle, but in brief:

 - `'apply'` hook: `snapshot` is the "old" snapshot, before the op is applied
 - `'commit'` hook: `snapshot` is the "new" snapshot, and has had the op applied, but not yet committed
 - `'afterWrite'`: `snapshot` has been saved to the database

In general, if you want to make changes to metadata, the `'commit'` hook is a good place to do it, as that's the op and the snapshot just before being written to the database.

> Can you point me to where in the documentation I can learn more about how the databases are utilized/configured

I'm not entirely sure what you mean by "utilized/configured" here, but databases are handled by the [database adapters](https://share.github.io/sharedb/adapters/database), so database-specific docs will be in those repos.

> Would something like this work?

I think you're setting metadata on your op, not on your snapshot? I thought you wanted to update your snapshot? You can make changes to the snapshot in the `'commit'` hook before writing:

```js
backend.use('commit', (request, callback) => {
  request.snapshot.m.my_custom_field = 'hello';
  callback();
});
```
