### ISSUE TITLE
npm run build cmd not working

### ISSUE THREAD

**Issue by ChauhanVinita** [share/sharedb#466]
While trying the example source code of rich-text-presence  (https://github.com/share/sharedb/tree/master/examples/rich-text-presence)  and other ,I am not able to create the bundle.js using npm run build cmd.

**Comment by alecgibson** [comment]
This works fine for me locally. Can you please provide the error you're getting, along with the version of Node and npm?

**Comment by ChauhanVinita** [comment]
npm version is 6.14.10
node version is v14.15.4
$ npm run build

> collab-sharedb@1.0.0 build C:\Collaborate\Collab_Presence
> mkdir -p static/dist/ && ./node_modules/.bin/browserify client.js -o static/dist/bundle.js

The syntax of the command is incorrect.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! collab-sharedb@1.0.0 build: `mkdir -p static/dist/ && ./node_modules/.bin/browserify client.js -o static/dist/bundle.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the collab-sharedb@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


Thanks

**Comment by alecgibson** [comment]
I see. What sort of shell are you running in?

**Comment by ChauhanVinita** [comment]
git bash

**Comment by alecgibson** [comment]
Can you try replacing it with this:

```
"build": "./node_modules/.bin/browserify client.js -o static/dist/bundle.js",
```

**Comment by alecgibson** [comment]
Sorry, or even this:

```
"build": "browserify client.js -o static/dist/bundle.js",
```

**Comment by ChauhanVinita** [comment]
Thanks  a lot ,its working
