### ISSUE TITLE
What's the purpose of applyStack in doc.js

### ISSUE THREAD

**Issue by happy15** [share/sharedb#475]
hi there,

from the code and comments I cannot quite understand the purpose of applyStack in doc.js.

For example, 
1. what's the meaning of "applying an op incrementally"?
2. is it possible for applyStack.length to get longer during _otApply?

Some introduction is much appreciated.

Thanks in advance.

**Comment by alecgibson** [comment]
Duplicate of https://github.com/share/sharedb/issues/474

**Comment by happy15** [comment]
Thanks for the cross linking.

I will paste my questions there and close this.
