### ISSUE TITLE
How to store userId with ops and snapshot?

### ISSUE THREAD

**Issue by Ashima246** [share/sharedb#477]
I am using StringBinding to submit operation and using cosmosDb to store ops and snapshot. Now I want to show which user is currently editing the doc, so for that I want to store userId along with ops and snapchat. How can I achieve this?

**Comment by alecgibson** [comment]
https://share.github.io/sharedb/middleware/op-submission#commit

**Comment by Ashima246** [comment]
> https://share.github.io/sharedb/middleware/op-submission#commit

How to set and send userId from the frontend?

**Comment by alecgibson** [comment]
You should know which user sent the op from their authentication on the server.
