### ISSUE TITLE
publish op

### ISSUE THREAD

**Issue by wangjianweiwei** [share/sharedb#478]
<img width="750" alt="11111111111" src="https://user-images.githubusercontent.com/41533289/120584905-5f9f1680-c463-11eb-91e5-7ab8ce5c3985.png">

I am in a similar situation. If Client B continues to submit data, does it affect the accuracy of the snapshot

**Comment by alecgibson** [comment]
Have you got a reproducible case of this happening? In theory ShareDB should be relatively robust to flaky connections, etc. In the worst case, it just hard resets the client, which might lose client-side data, but won't affect server-side data.
