### ISSUE TITLE
Display user editing the doc

### ISSUE THREAD

**Issue by Ashima246** [share/sharedb#479]
I want to display the list of users editing the doc to all other users connected to the socket connection.

**Comment by alecgibson** [comment]
https://share.github.io/sharedb/presence

**Comment by Ashima246** [comment]
I am using typed presence, when I edit the doc value I get this: this._doc.type.transformPresence is not a function.

**Comment by HPieters** [comment]
Do you have an example @Ashima246 that would make things easier? And is the doc type "rich-text", if you look in the docs it says `Currently, only rich-text supports presence information`.

**Comment by alecgibson** [comment]
Yes sounds like you're not using `rich-text`: https://github.com/share/sharedb/issues/423

As I mentioned in the other issue, we should improve our error message in this case.

**Comment by Ashima246** [comment]
Yes, I am not using rich-text. Thank you!
But I will be requiring presence information for JSON so will try to implement it.
