### ISSUE TITLE
Usage without mongo

### ISSUE THREAD

**Issue by axelson** [share/sharedb#48]
From the docs it is not clear if it is possible to use livedb/ShareJS without mongodb.

> To use it, you need a database to actually store your data in. A database wrapper for mongo is available in share/livedb-mongo. I hope to add more over time.

Does this mean it is not possible to use ShareJS without mongodb? I already have a redis and mysql instance, I'd rather not add mongo just for live editing capabilities.

**Comment by zag2art** [comment]
If you want to use mysql you should have livedb-mysql driver (like https://github.com/share/livedb-mongo). But the one have not written yet. If you want to try - just look at the my https://github.com/zag2art/livedb-mongo-memory inmemory mongodb driver.

**Comment by jclem** [comment]
I have a [PostgreSQL driver](https://github.com/usecanvas/livedb-postgresql) that I've been running in production.

**Comment by axelson** [comment]
Thanks @jclem I had no idea that there was even a PostgreSQL driver, I'll try and check that out.

**Comment by thejsj** [comment]
I also wrote an integration with RethinkDB which uses the same testing suite as the mongo driver

[GitHub](http://github.com/thejsj/livedb-rethinkdb)

[npm](https://www.npmjs.com/package/livedb-rethinkdb)

[Demo](livedb-rethinkdb.thejsj.com)

**Comment by jhchen** [comment]
I think @jclem deserves the credit :)

**Comment by thejsj** [comment]
Oh, wrong autocomplete entry. Sorry! @jclem nice work on the Postgres driver!

**Comment by curran** [comment]
This issue can be closed, as there is solid in-memory support, and also Mingo support.

**Comment by WinMinTun** [comment]
Hi everyone and @axelson, I have just written Sharedb MySQL adapter. Pls check and comment https://github.com/WinMinTun/sharedb-mysql

**Comment by curran** [comment]
@WinMinTun Very nice!

**Comment by alecgibson** [comment]
Closing, because there are indeed multiple adapters available.
