### ISSUE TITLE
'fetchSnapshot' middleware

### ISSUE THREAD

**Issue by Kuzzy** [share/sharedb#491]
Hello!

Is there any way to catch `fetchSnapshot` method on backend? 

My use case is to make authorization for fetching snapshots from client on backend. I've tried `readSnapshots` middleware but it fires on `doc.subscribe` too, but I need to separate this events somehow. For example, some users can read and write doc, but can't read history (with fetchSnapshot method), other users can do both things.

Thanks!

**Comment by dwinrick-lever** [comment]
There isn't a middleware action to separate the two.

But try inspecting the request object in your `readSnapshot` middleware. I believe the request object will tell you if it's from a `fetch` or a `subscribe` on the client side.

**Comment by alecgibson** [comment]
You can distinguish between types of snapshot read using the [`snapshotType`](https://share.github.io/sharedb/middleware/actions#readsnapshots) property.

**Comment by Kuzzy** [comment]
@alecgibson oh, sure. Looks like I was blind when read documentation :) Thanks a lot!
