### ISSUE TITLE
Send the op again after disconnecting

### ISSUE THREAD

**Issue by wangjianweiwei** [share/sharedb#497]
After the connection is disconnected, the inflightOp will be re-placed in the pendingOps, and then sent again after reconnecting, am I understand? If that's true, will there be repeated ops?

For example, disconnected before receiving ack, is Sharedb compatible with this situation?

Thank you

**Comment by alecgibson** [comment]
https://github.com/share/sharedb/issues/470#issuecomment-876196787

**Comment by wangjianweiwei** [comment]
Thank you for your timely reply. I understand.
