### ISSUE TITLE
Doc utility method for creating a snapshot

### ISSUE THREAD

**Issue by curran** [share/sharedb#500]
Tracking this idea out of a discussion in https://github.com/share/sharedb/pull/493

As a user of ShareDB in the context of an isomorphic JavaScript app, I want to be able to use `ingestSnapshot` to ingest data that was transferred to the client externally to the client's ShareDB connection, so that the number of times a given document is queried for in the database and transferred over the wire is reduced from 2 (server side fetch, client side subscribe without `ingestSnapshot`) to 1 (server side fetch only).

Proposed API: `Doc.createSnapshot()`. This makes sense to invoke only after a successful fetch or subscribe.

**Comment by alecgibson** [comment]
Sounds sensible to me. I guess the opposite of "ingest" is "egest", but it doesn't sound like a nice/common word, so "create" is fine by me.

**Comment by curran** [comment]
Lol egest.

There's also https://share.github.io/sharedb/api/connection#fetchsnapshot

**Comment by curran** [comment]
Closing this because for my use case I can use `fetchSnapshot`.

**Comment by curran** [comment]
On second thought, it might be quite useful to have a utility method for generating a snapshot from a doc.

Use case:
 * We have an API where the response should be a valid snapshot, for client side ingestion.
 * If the document already exists, we can use `fetchSnapshot`,
 * but if the document does not exist, we need to create it and return its snapshot.

In the case where the document does not exist yet, it would be great to have a method on `Doc` that could generate a snapshot, rather than first create the doc and then execute `fetchSnapshot` against it.

**Comment by curran** [comment]
Notes from call: Also useful for offline use cases.
