### ISSUE TITLE
Make CI Sane

### ISSUE THREAD

**Issue by curran** [share/sharedb#509]
CI currently runs `npm run lint`, which is failing on `master`.

This causes all PRs to fail CI, such as [this one](https://github.com/share/sharedb/pull/508/checks?check_run_id=3393270552#step:6:24).

**Comment by curran** [comment]
Still not quite sane.

![image](https://user-images.githubusercontent.com/68416/131561481-3200cb46-7eea-4c7c-a57a-d2c6efbb3971.png)

https://github.com/share/sharedb/pull/508/checks?check_run_id=3475145150

**Comment by alecgibson** [comment]
Yeah we need to drop Node.js 10 support in a breaking change

**Comment by curran** [comment]
Got it. Thanks!

Related https://github.com/share/sharedb/issues/483
