### ISSUE TITLE
Custom messages in the redis scaled sharedb

### ISSUE THREAD

**Issue by yaroslavputria** [share/sharedb#519]
Hi All,

There is a way to implement custom messaging through the sharedb ws connection: https://github.com/share/sharedb/issues/104#issuecomment-240596912.
Do you know how this can be achieved for the redis scaled approach? - Clients connected to different sharedb instances should receive custom messages invoked on one of the servers.

**Comment by alecgibson** [comment]
What's the use-case here? Can you provide a bit more details on what it is you're trying to achieve?

**Comment by yaroslavputria** [comment]
Hi @alecgibson 

Before I scaled sharedb I had implemented custom messaging through the sharedb ws - it used to notify that doc becomes private using `agent.send({type, data})`. On the connect state I store agents and later if they are subscribed to the corresponding doc, I send them a notification that the doc is now private. Now I don't have agents from the different sharedb instances.

**Comment by alecgibson** [comment]
We don't really support sending non-ShareDB messages over either the websocket or over pubsub. Your best, most robust bet is to set up your own, separate channel.

If you're hellbent on reusing ShareDB infrastructure, I'm afraid I can't offer much assistance. You're free to rummage around in the source code. A good place to start is investigating the point at which ops are broadcast to other servers:

https://github.com/share/sharedb/blob/46c4aba0f9cc538dabca0c0c3a5d5f565fff9671/lib/submit-request.js#L178

**Comment by yaroslavputria** [comment]
That's what I'm currently doing. Thanks for the answers!
