### ISSUE TITLE
Is sharedb an implementation of the Jupiter OT algorithm?

### ISSUE THREAD

**Issue by nieyuyao** [share/sharedb#526]
I'm learning sharedb and some papers about OT algorithm. So I have a question as the title shown. It is not an urgent issue. 😋

**Comment by curran** [comment]
See

https://github.com/ottypes/json0

https://github.com/ottypes/json1

**Comment by pykenny** [comment]
I think OP's trying to understand if OT implementation in sharedb (along with OT type implementations) fits to one of the algorithm mentioned in [OT's Wikipedia article], or perhaps one of the two workable (and centuralized) solutions mentioned in [Martin Kleppmann's talk](https://images.ctfassets.net/s600jj41gsex/3uTL8JEqiqecKDjugRtcdO/78568b05622cc3d0fdbb0b46d09ccf1d/Screen_Shot_2019-11-29_at_2.10.39_pm.png).

Just skimmed through JSON0 and [JSON1's spec](https://github.com/ottypes/json1/blob/master/spec.md) and barely find out information about the actual algorithm/paper/reference implemented.
