### ISSUE TITLE
Are submitted ops atomic?

### ISSUE THREAD

**Issue by sr258** [share/sharedb#541]
I submit ops to my ShareDB server that contain several entries, like this:

```
[
      {
        p: ["phase"],
        od: "question",
        oi: "review",
      },
      {
        p: ["scores"],
        od: oldscores,
        oi: newScores,
      },
]
```

In the submitting client, these two changes are applied to the document all at once and I only receive one call to the "op" event I've registered to by calling `doc.on("op", () => {...});`.

In other clients, however, the event handler is called twice and there are intermediate states, in which the `phase` property is already updated but `scores` isn't. The server logs only one submission and the middleware is only called once.

Is this behavior to be expected or am I doing something wrong? I'd like to avoid having these intermediate states in the client, as it complicates UI rendering. Is there a way to work around this?

**Comment by alecgibson** [comment]
Sounds like you want the [`'op batch'`](https://share.github.io/sharedb/api/doc#op-batch) event instead of `'op'`.

**Comment by sr258** [comment]
Thanks a lot. That solved my issue. I wonder whether the behavior of the submitting client is as intended, as I it doesn't fire multiple 'op' events but only one, even if there are multiple ops in a batch submission.

**Comment by alecgibson** [comment]
It's definitely deliberate: we [check for a falsy `source`](https://github.com/share/sharedb/blob/fbd16ef2792dad13fa214485e2a572099b1ba7ba/lib/client/doc.js#L621) (which means the op is remote).

However, I'm not entirely sure why this behaviour was decided on.

**Comment by sr258** [comment]
Alright, no reason to keep this issue open then. Thank you for the help!
