### ISSUE TITLE
Install failed on Node 4.0

### ISSUE THREAD

**Issue by geakstr** [share/sharedb#55]
Hello. LiveDB not installing on new node, this is part of log https://gist.github.com/geakstr/d6e70941a10df7208582

**Comment by Dignifiedquire** [comment]
Looks like [node-hiredis](https://github.com/redis/hiredis-node) needs to be updated to the latest version.

**Comment by josephg** [comment]
hiredis is (should be) an optional dependancy. Actually all the redis stuff is only required if you're distributing across multiple servers. Maybe we should make that relationship explicit through the modules.

**Comment by riston** [comment]
Same issue with Node v4.x installation, but if using the "external" redis instance like in example then there should no problems ?

```
var redis = require('redis');
client1 = redis.createClient(6379, '192.168.1.123', auth_pass:'secret');
client2 = redis.createClient(6379, '192.168.1.123', auth_pass:'secret');

driver = livedb.redisDriver(oplog, client1, client2);
```

**Comment by nateps** [comment]
Fixed in sharedb rewrite.
