### ISSUE TITLE
Why is src assigned after the send?

### ISSUE THREAD

**Issue by nieyuyao** [share/sharedb#557]
The `op` is sent at `doc`:

```javascript

Doc.prototype._sendOp = function() {
  // ...
  this.connection.sendOp(this, op);

  // src isn't needed on the first try, since the server session will have the
  // same id, but it must be set on the inflightOp in case it is sent again
  // after a reconnect and the connection's id has changed by then
  if (op.src == null) op.src = src;
};

```
So that `src` is undefined in message which is sent:

```javascript

Connection.prototype.sendOp = function(doc, op) {
  // Ensure the doc is registered so that it receives the reply message
  this._addDoc(doc);
  var message = {
    a: 'op',
    c: doc.collection,
    d: doc.id,
    v: doc.version,
    src: op.src,
    seq: op.seq,
    m: op.m
  };
  if ('op' in op) message.op = op.op;
  if (op.create) message.create = op.create;
  if (op.del) message.del = op.del;
  this.send(message);
};

```

This doesn't cause problems because the agent also keeps this value. But I don't understand why not set `src` before ` this.connection.sendOp(this, op)`?

**Comment by alecgibson** [comment]
I don't know for sure (this code is at least 7yrs old!), but I suspect from the comment ("src isn't needed on the first try") this was a tiny performance thing to keep the message payload size down.

**Comment by josephg** [comment]
Yeah, I wouldn't be surprised. That sounds like the sort of silly microoptimizations I have a tendency to make, which often get me in trouble.
