### ISSUE TITLE
Callback when user disconnects from presence

### ISSUE THREAD

**Issue by chloekek** [share/sharedb#565]
Presence can raise [two types of events](https://share.github.io/sharedb/api/presence#events), `receive` and `error`. But neither seems to be raised when a peer disconnects. Is there a way to get notified when a peer disconnects, so that its presence can be removed from the local state? The server doesn’t seem to send a message to the client when a peer disconnects.

**Comment by alecgibson** [comment]
Yes that's right. We should probably update the documentation to draw attention to that.
