### ISSUE TITLE
Issue in the "async" dependency

### ISSUE THREAD

**Issue by yaroslavputria** [share/sharedb#573]
Hi!
My Snyk scanning found the Prototype Pollution issue.
Could you please update the "async" dependency 2.6.3 -> 2.6.4?

**Comment by alecgibson** [comment]
Since this is a [patch update](https://docs.npmjs.com/about-semantic-versioning), you should be able to bump this in your own lockfile without us needing to do anything. Try deleting your lockfile and `node_modules` and reinstalling from scratch.

**Comment by yaroslavputria** [comment]
Thanks @alecgibson
