### ISSUE TITLE
sharedb.client is not a function

### ISSUE THREAD

**Issue by lslzl3000** [share/sharedb#58]
It seems that livedb is renamed or rebuilt with sharedb, but the official demo or readme(in both share & sharedb doc) still use old APIs, such as .client() is actually not available in new sharedb. 
I have faced errors with this new sharedb. Could you update your docs & demos please, thanks

**Comment by lslzl3000** [comment]
And I think, the current shareJS repo(still use local module livedb) is not ready for sharedb

**Comment by lslzl3000** [comment]
Is there anyone working on this?

**Comment by ejfrancis** [comment]
yeah I'm having a hard time trying this out as well, it looks like the docs need an update to reflect the current API

**Comment by lslzl3000** [comment]
Did u find a way to make it work?

**Comment by ejfrancis** [comment]
nope, the API has evidently changed quite a bit since the docs were written and I wasn't able to figure it out with a couple hours of poking around and trial/error

**Comment by nateps** [comment]
Documentation in readme definitely still in flight, but API is stabilizing now. You can refer to the tests now for usage if interested. I'm going to close this issue since it is specific, but I realize the new API needs documentation.
