### ISSUE TITLE
CI Broken on 3.3.0 release commit

### ISSUE THREAD

**Issue by curran** [share/sharedb#600]
I'm noticing that CI is broken on the most recent release.

https://github.com/share/sharedb/commit/c587181b356e5dcb8a93e022d0f1325255be4b41

It fails on Node 16 only, with the following error:

```
npm ERR! Could not resolve dependency:
npm ERR! peer sharedb@"^1.0.0-beta || ^2.0.0" from sharedb-mingo-memory@1.2.0
npm ERR! node_modules/sharedb-mingo-memory
npm ERR!   dev sharedb-mingo-memory@"^1.1.1" from the root project
```

Related to https://github.com/share/sharedb-mongo/issues/147

**Comment by alecgibson** [comment]
It's not to do with that commit; the build is flaky as per the linked issue. I've rerun the build and it's green now.
