### ISSUE TITLE
`TypeError Cannot read properties of null (reading 'callback')` when receiving subscribe response with no inflight subscribe

### ISSUE THREAD

**Issue by alecgibson** [share/sharedb#605]
We're getting this error:

![app rollbar com_a_Reedsy_fix_item_Reedsy-Editor_10814_occurrence_322889472575](https://user-images.githubusercontent.com/12036746/232774600-9e720c6e-4008-4cdc-a612-8f4ac4d21d3c.png)

The error is happening because a subscribe response is being received over the WebSocket, but there's no `inflightSubscribe` set. 

I've rummaged around in the code (which I wrote 😅 🙈 ) and I'm not really sure how we get into this state.

As far as I can tell:

- we should only get a subscribe response after sending a subscribe request
- a subscribe request can only be flushed [when `!!connection.canSend`](https://github.com/share/sharedb/blob/ab2341eb794938ac6e5b155d21b0e88029b32a02/lib/client/doc.js#L466)
- if the connection is closed before the response is received, the `inflightSubscribe` is [put back](https://github.com/share/sharedb/blob/ab2341eb794938ac6e5b155d21b0e88029b32a02/lib/client/doc.js#L402-L403) into the `pendingSubscribe` queue
- the subscribe [will be retried](https://github.com/share/sharedb/blob/ab2341eb794938ac6e5b155d21b0e88029b32a02/lib/client/doc.js#L393) when the socket reconnects
- the only way to hit this error state is to have unset (or never set?!) `inflightSubscribe`, which only happens: 
  - [before a subscribe request is sent](https://github.com/share/sharedb/blob/ab2341eb794938ac6e5b155d21b0e88029b32a02/lib/client/doc.js#L69)
  - [when the connection is closed](https://github.com/share/sharedb/blob/ab2341eb794938ac6e5b155d21b0e88029b32a02/lib/client/doc.js#L403)
  - [after handling a subscribe response](https://github.com/share/sharedb/blob/ab2341eb794938ac6e5b155d21b0e88029b32a02/lib/client/doc.js#L311)
- from the stack trace, it's clear we're receiving a message, so we know the socket is connected

**Comment by alecgibson** [comment]
Okay, I think I'm getting somewhere with this. The issue appears to be to do with our reconnecting websocket. It looks like this series of events is happening:

1. Use reconnecting socket to connect to ShareDB
2. Wait until connection fully established
3. Call `socket.close()`
4. **SYNCHRONOUSLY** subscribe a document (or do it very, very soon after calling `socket.close()`)
5. ShareDB hasn't yet received the socket's `onclose()` call (probably because the socket is still hanging up)
6. ShareDB calls `connection.send()` and submits a subscribe request down the (closing) socket
7. `onclose()` called, and ShareDB updates its state to `disconnected`, pushes inflight subscribe back onto pending queue
8. Reconnect socket
9. **THIS IS THE KEY**: for some reason, the reconnecting socket has buffered or retried the message sent whilst closing, and submits this as soon as the socket opens, even before ShareDB has started its handshake. ShareDB proceeds under the assumption that its previous message has been discarded, which it hasn't.
10. ShareDB finishes its handshake, and retries its pending subscribe
11. Server processes request that was sent before handshake, and the inflight subscribe calls its callback
12. The *actual* request that was sent is processed, and returns, but finds no inflight subscribe and throws

<img width="559" alt="Screenshot 2023-04-26 at 15 18 00" src="https://user-images.githubusercontent.com/12036746/234604664-ceb63bcd-6b40-4c73-ad8c-f135c9942af9.png">

There's a lot of moving parts here, but I'm pretty sure this is the rough shape of the problem.

This could well be a bug in our reconnecting socket library, but regardless of that, I guess it raises a question around how ShareDB should act before its handshake has completed: should the server just bin any messages we receive before this? The client already tries to avoid sending messages before the handshake, so we *should* be able to assume anything sent before the handshake is rubbish?

**Comment by alecgibson** [comment]
Ha yes, okay `reconnecting-websocket` will [buffer messages](https://github.com/pladaria/reconnecting-websocket/blob/05a2f7cb0e31f15dff5ff35ad53d07b1bec5e197/reconnecting-websocket.ts#L252-L263) if you call `send()` after the socket has been closed.

I guess this is probably a valid thing for a reconnecting socket to do in order to keep its API roughly aligned with a "vanilla" `WebSocket` that's just always connected.

I think we should make ShareDB behave "sensibly" if clients decide to retry messages on reconnection, before the handshake has happened. Will put together a PR and we can discuss there I guess.

**Comment by alecgibson** [comment]
Hmm had a very quick look at this and actually I'm not sure how best to do this without making a breaking change to our protocol. 

Outline of v1.0 vs 1.1 protocol here: https://github.com/share/sharedb/pull/341

The crux of it is that v1.0 just sends an `init` to the client, and doesn't wait for anything back from the client, so as far as a v1.0 server is concerned, it can just start processing any messages that come in as soon as it binds.

A v1.1 server can disregard any messages it receives before the client's `hs` message, but I think(?) there's no way for a server to *really* tell the difference between:

 - a legitimate message sent by a v1.0 client
 - a spurious retried message sent by a v1.0 client
 - a spurious retried message sent before handshake by a v1.1 client

We could potentially do something like buffer for some time, or `n` messages before we assume the handshake is never coming (ie is a v1.0 client), but this starts to feel janky.

Maybe we should just do something simple like log a warning if an `Agent` receives a message before handshake (which consumers can turn off if they know they still have v1.0 clients kicking about for some reason...?).

**Comment by ericyhwang** [comment]
Alec says it's when the sharedb client tries to send data while the socket is in CLOSING. Unfortunately there's no 'closing' event.

In addition to the server change above, we are also considering specifically having the client check for `socket.readyState === State.OPEN` before trying to send, to catch cases where the socket is in CLOSING state.
