### ISSUE TITLE
API Support for Presence Notifications

### ISSUE THREAD

**Issue by curran** [share/sharedb#632]
Greetings!

I'm building a feature on the [Presence API](https://share.github.io/sharedb/presence) wherein my app shows notifications when users join or leave the session.

I also want to build a feature that shows the list of present users at any given point in time.

I'm running up against what seems to be limitations in the presence API, namely: It's unclear if it's possible to know, on page load, who is currently present in the document.

Use cases:
 * When a user loads the app, the app should display a list of users who are already in the document
 * When a user who is already present in the session emits a presence update, a notification that they joined the session should not appear

Here's the current workaround, which tracks who is present based on the 'receive' events:

```js
const knownPresenceIds = new Set();

presence.on('receive', (presenceId, update) => {
  if (update === null) {
    // The remote client is no longer present in the document
    if (knownPresenceIds.has(presenceId)) {
      // Handle user left notification
      knownPresenceIds.delete(presenceId);
    }
  } else {
    if (!knownPresenceIds.has(presenceId)) {
      // Handle user joined notification
      knownPresenceIds.add(presenceId);
    }
    // Handle other presence updates like cursor move
  }
});
```

In this context, is there any way to pre-populate `knownPresenceIds` on page load? Or is this outside the scope of the ShareDB Presence API? Many thanks!

**Comment by alecgibson** [comment]
Whenever you subscribe a presence, you should automatically get updates from all other connected users.

**Comment by curran** [comment]
For a given update, is there a way to differentiate the following cases?

 * if it is from a user that is already connected (before you joined)
 * if it is from a user that connected after you joined

Maybe one way is to set a timer for 1 second or so after you connect, and if you get the update before that window we can assume the user had joined before you?

**Comment by alecgibson** [comment]
You can manually create presence IDs for your clients, so you could create an ID that contains the timestamp that the client joined at (if you use `ObjectId` this information will already be encoded.

**Comment by curran** [comment]
Whoah that's a fantastic idea! Thank you. I'll give it a shot.

That would solve the problem, as we could then compare timestamps and figure out which remote clients joined before vs. after we joined.

**Comment by alecgibson** [comment]
You also have another couple of options.

The first is that you can amend the presence message in the `Agent`'s [`receivePresence` hook](https://share.github.io/sharedb/middleware/actions#receivepresence). In middleware, you'll have access to [`agent.connectTime`](https://github.com/share/sharedb/blob/3cb6a5166217414b2c371b4497fc006ecb1069e4/lib/agent.js#L30). This would let you set a more reliable server-based timestamp.

The second is that the client can just send extra meta in their presence payload, which depends on the presence implementation. For example I ensured that `rich-text`'s implementation [keeps arbitrary metadata](https://github.com/ottypes/rich-text/blob/b53cd97690804e544370423ce27c6d852abb2c7f/test/presence.js#L41-L46) when transforming presence, so you can send extra information along with the actual presence information.

**Comment by curran** [comment]
Thanks so much for the advice! We were able to get it working based on checking timestamps.
