### ISSUE TITLE
failed process file : failed send RangeError: Invalid string length

### ISSUE THREAD

**Issue by icoco** [share/sharedb#655]
```
failed send RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at Connection.send (code-server/node_modules/sharedb/lib/client/connection.js:493:27)

```

looks the file content too larger ?

**Comment by alecgibson** [comment]
Please provide a minimal repro case

**Comment by icoco** [comment]
I trace the log, it cause the field 'files' , if the 'files' value is large, then report the error bellows:
 ```
...  RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at Connection.send....
```
the log message : 

```
sharedb/lib/client/connection.js->SEND {
  a: 'op',
  c: 'documents',
  d: 'af03d59c381bcfc4a1816d342604fabe967c6d5a53e61459dff8c03b7be996c6',
  v: null,
  src: undefined,
  seq: 2,
  x: {},
  create: { type: 'p', data: { files: [Object] } }
}

```

data.files is very large object that contains many key=>value  data

**Comment by alecgibson** [comment]
This is a general issue with you [running out of memory](https://github.com/nodejs/node-v0.x-archive/issues/14170). There will always be some limit there, and it looks like you've found it.

I'd first ask yourself from an architectural point of view just why this object has to be so large: transmitting this volume of data (presumably hundreds to thousands of MB?) down the wire is going to be exceptionally slow for your clients; and for any other clients who have to download this document.

If — for some reason — this is **absolutely necessary**, you should chunk your object up and submit smaller update ops. This loses the atomicity of a single create, but is the only practical solution for an arbitrarily large object.

**Comment by icoco** [comment]
I see, so can not put a directory that contains large files in to Sharedb document
