### ISSUE TITLE
How to implement Presence with 'rich-text' as 'json1' subtype?

### ISSUE THREAD

**Issue by benjismith** [share/sharedb#675]
I'm using `json1` as the primary type in my application, and I have `rich-text` objects nested within those records.

I'd like to implement the Presence API, but the [ShareDB docs](https://share.github.io/sharedb/presence) say that `Currently, only rich-text supports presence information`. There are no examples of creating a rich-text presence on a nested object. Is that a simple straightforward case, or more complicated?

I've been reading through the issue report for [Issue #423: transformPresence is not a function](https://github.com/share/sharedb/issues/423) so that I can better understand how the Presence API works, and thinking through possible solutions, but I thought I'd ask for advice here first. Do you have any suggestions? If there need to be any changes to the raw json1 type or to the ShareDB presence implementation, I'd be happy to work on it and contribute my code, if you're interested...

**Comment by alecgibson** [comment]
I've got a PR open against `json0`: https://github.com/ottypes/json0/pull/48 (@ericyhwang we should actually get back to looking at that!), so you can probably use that as some vague inspiration/starting point.

The `json0` implementation includes handling text transforms, as well as embedded subtypes (which would include `rich-text`). I'm completely unfamiliar with `json1`, but I imagine that it should be a similar thing...?

**Comment by benjismith** [comment]
Thank you, that's very helpful!
