### ISSUE TITLE
Add contributor guidelines

### ISSUE THREAD

**Issue by avital** [share/sharedb#80]

**Comment by curran** [comment]
Having contributor guidelines would definitely be useful. I have made a number of pull requests, and I'm not sure why they are not being reviewed or merged. My guess is that it's a lack of time on the part of the maintainers, but I also wonder if I'm doing something wrong, or if something more is expected from outside contributors like me (e.g. a detailed explanation of why the change is required). Having clarity on what's expected of contributors would be great.

**Comment by curran** [comment]
I suggest we close this in favor of https://github.com/share/sharedb/issues/240

**Comment by alecgibson** [comment]
Agreed with @curran
