### ISSUE TITLE
Leaderboard example is not working

### ISSUE THREAD

**Issue by juanecabellob** [share/sharedb#89]
I've tried to run the leaderboard example and the websocket-json-stream is not working. 

It had also a lot of missing dependencies which are not included in package.json.The missing ones were `serve-static` and `sharedb-mingo-memory`

Error:
util.inherits(WebSocketServerStream, Duplex);
              ^
ReferenceError: WebSocketServerStream is not defined
    at Object.<anonymous> (sharedb-master/examples/leaderboard/node_modules/websocket-json-stream/index.js:23:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (sharedb-master/examples/leaderboard/server/index.js:6:27)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by khoaho** [comment]
I have the Leaderboard example working. We need to add missing dependencies. Here is my updated  package.json:

> {
  "name": "leaderboard",
  "version": "0.0.1",
  "description": "React Leaderboard backed by ShareDB",
  "main": "server.js",
  "scripts": {
    "build": "mkdir -p dist/ && ./node_modules/.bin/browserify -t [ babelify --presets [ react ] ] client/index.jsx -o dist/bundle.js",
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server/index.js"
  },
  "author": "Tom Coleman <tom@percolatestudio.com> (https://tom.thesnail.org/)",
  "contributors": [
    "Tom Coleman <tom@percolatestudio.com> (https://tom.thesnail.org/)",
    "Avital Oliver <avital@aoliver.org> (https://aoliver.org/)"
  ],
  "license": "MIT",
  "dependencies": {
    "classnames": "^2.2.5",
    "connect": "^3.4.1",
    "react": "^15.1.0",
    "react-dom": "^15.1.0",
    "serve-static": "^1.11.1",
    "sharedb": "^0.11.37",
    "through2": "^2.0.1",
    "underscore": "^1.8.3",
    "websocket-json-stream": "^0.0.1",
    "websocket-stream": "^3.2.1",
    "ws": "^1.1.0"
  },
  "devDependencies": {
    "babel-preset-react": "^6.5.0",
    "babelify": "^7.3.0",
    "browserify": "^13.0.1"
  }
}


The server will work, but it still asks for missing http://localhost:8080/dist/bundle.js as seen in the Counter example. Where is the bundle.js file?

**Comment by avital** [comment]
You're right, I'll fix the example and push a fix shortly.

And bundle.js is generated by `npm run build`, which I've updated the README to explain before the section on running the server.

**Comment by avital** [comment]
I just pushed a fix to the dependencies of leaderboard, and also a new version of both `sharedb` itself and `websocket-json-stream`.

Run:
```js
npm update
npm run build
npm start
```

Let me know if this works for you.

**Comment by khoaho** [comment]
Here is my updated package.json to build in Windows with `npm run build:windows`

>{
  "name": "leaderboard",
  "version": "0.0.1",
  "description": "React Leaderboard backed by ShareDB",
  "main": "server.js",
  "scripts": {
    "build": "mkdir -p dist/ && ./node_modules/.bin/browserify -t [ babelify --presets [ react ] ] client/index.jsx -o dist/bundle.js",
    "build:windows": "mkdir dist & node_modules\\.bin\\browserify -t [ babelify --presets [ react ] ] client\\index.jsx -o dist\\bundle.js",
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server/index.js"
  },
  "author": "Tom Coleman <tom@percolatestudio.com> (https://tom.thesnail.org/)",
  "contributors": [
    "Tom Coleman <tom@percolatestudio.com> (https://tom.thesnail.org/)",
    "Avital Oliver <avital@aoliver.org> (https://aoliver.org/)"
  ],
  "license": "MIT",
  "dependencies": {
    "classnames": "^2.2.5",
    "connect": "^3.4.1",
    "react": "^15.1.0",
    "react-dom": "^15.1.0",
    "serve-static": "^1.11.1",
    "sharedb": "^1.0.0-beta",
    "through2": "^2.0.1",
    "underscore": "^1.8.3",
    "websocket-json-stream": "^0.0.3",
    "ws": "^1.1.0"
  },
  "devDependencies": {
    "babel-preset-react": "^6.5.0",
    "babelify": "^7.3.0",
    "browserify": "^13.0.1"
  }
}

**Comment by serip88** [comment]
@avital Thank you,

It's work for me

P/s: and for someone get Error : cannot find module 'sharedb-mingo-memory'
run: 
npm i sharedb-mingo-memory

**Comment by curran** [comment]
FWIW I submitted a pull request that adds the missing dependency, but it has been ignored. https://github.com/share/sharedb/pull/117

**Comment by avital** [comment]
#117 is now merged. Closing this as I believe this fixes the issue. Re-open if not. Sorry for the slow response.

**Comment by curran** [comment]
Awesome, thanks!
