### ISSUE TITLE
Counter example is not working

### ISSUE THREAD

**Issue by khoaho** [share/sharedb#91]
It's missing bundle.js at http://localhost:8080/dist/bundle.js . Where is this JavaScript file?

Thank you.

**Comment by geakstr** [comment]
Do `npm run build` before

**Comment by avital** [comment]
Yes, it should work after `npm run build`. I changed the README so that that step appears first. Let me know if it works for you.

**Comment by khoaho** [comment]
I am using node.js v6.3.1 with npm v3.10.3.

"npm run build" raises error: "npm ERR! missing script: build"

So I use "npm build". It works silently without error. However, the dist directory is not created after build. I have to copy manually the dist folder from node_modules\sharedb\examples\counter. After that, "npm start" will work.

Thanks.

**Comment by avital** [comment]
I'm surprised. I just verified that `npm run build` runs on my machine with npm v3.10.3. Are you running `npm run build` while inside the examples/counter directory?

**Comment by khoaho** [comment]
I am using Windows 10, node.js v6.3.1 with npm v3.10.3. I ran `npm run build` inside examples/counter directory. Here is the error details:

c:\Data\GitHub\sharedb\examples\counter>npm run build

> counters@0.0.1 build c:\Data\GitHub\sharedb\examples\counter
> mkdir -p dist/ && ./node_modules/.bin/browserify client.js -o dist/bundle.js

The syntax of the command is incorrect.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! counters@0.0.1 build: `mkdir -p dist/ && ./node_modules/.bin/browserify client.js -o dist/bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the counters@0.0.1 build script 'mkdir -p dist/ && ./node_modules/.bin/browserify client.js -o dist/bundle.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the counters package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mkdir -p dist/ && ./node_modules/.bin/browserify client.js -o dist/bundle.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs counters
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls counters
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Data\GitHub\sharedb\examples\counter\npm-debug.log

**Comment by zag2art** [comment]
I know that some guys use the https://github.com/derbyparty/generator-derby/blob/master/app/templates/_npm-shrinkwrap.json npm-shrinkwrap-file to force derby working in windows. Just as a workaround.

It solves "/", '\' browserify issues.

Maybe it helps.

**Comment by avital** [comment]
@khoaho You're right. We never tested this on Windows.

**Comment by khoaho** [comment]
I can make the build work in Windows by adding build:windows into scripts of package.json:

Counter example:
    "build:windows": "mkdir dist & node_modules\\.bin\\browserify client.js -o dist\\bundle.js",

Leaderboard example:
    "build:windows": "mkdir dist & node_modules\\.bin\\browserify -t [ babelify --presets [ react ] ] client\\index.jsx -o dist\\bundle.js",

Then we can build them in Windows with `npm run build:windows`

**Comment by ruimadeirab** [comment]
i tried this last message
doesnt show any error
 but still doesn't work for me
